### ISSUE TITLE
Visual indicator to show hierarchy when using select->fromQuery()

### ISSUE THREAD

**Issue by stefancrowe** [formers/former#164]
It would be good to have a visual representation of hierarchy when there are relationships associated with the Eloquent results passed to the fromQuery method of a select.

Example data structure
* Parent 1
 * Child 1 of Parent 1
 * Child 2 of Parent 1
* Parent 2
 * Child 1 of Parent 2
* Parent 3
* Parent 4
* ...

Current behaviour seems to put them in the correct order based on the relationships, but there's no indication of child items. Maybe indenting the children with hyphens or similar could be an option?

**Comment by claar** [comment]
Closing old inactive issues to make project maintainable.
