### ISSUE TITLE
[L4] Checkbox checked state does not get set properly

### ISSUE THREAD

**Issue by Stayallive** [formers/former#174]
When using a `Former::checkbox('field')` the `->check($value)` does nothing...

Use cases:
```php
{{ Former::open()->rules(Model\User::getValidationRules()) }}
    {{ Former::checkbox('field')->check(true) }} // Stays unchecked
{{ Former::close() }}

{{ Former::open()->rules(Model\User::getValidationRules()) }}
{{ Former::populate($user) }} // [ 'field' => 1 ]
    {{ Former::checkbox('field')->check(false) }} // Stays checked
{{ Former::close() }}

{{ Former::open()->rules(Model\User::getValidationRules()) }}
{{ Former::populate($user) }} // [ 'field' => 0 ]
    {{ Former::checkbox('field') }} // Is checked
{{ Former::close() }}
```

(The `Model\User::getValidationRules()` call spit out an array with `'field' => string 'in:0,1' (length=6)`)

A `dd($user->field)` gives `boolean false`. I'm puzzled... When populating it seems that a checkbox is alway checked regardless what is in the populated data or what you define in the `->check($value)`. For not populating it seems to be always off.

I have in the config:
```php
'push_checkboxes' => true,
'unchecked_value' => 0,
```

I have tried poking around in the source but i'm lost because the `check` method in the `Checkable` trait does not even seems to be called...

The only thing I can come up with is that is is some form of black magic :rainbow:

**Comment by claar** [comment]
Closing old inactive issues to make project maintainable.
