### ISSUE TITLE
Former's approach to field sizing

### ISSUE THREAD

**Issue by petercoles** [formers/former#209]
Former's current approach to field sizing is fine for Bootstrap 2 and Foundation 3. Alas it's incompatible with Bootstrap 3 and Foundation 4 too <sighs>. This issue is raised to explain the problems (for there are several), to propose a solution and to solicit feedback and views.

Currently field sizing means setting the field width. It's done by pre-pending the class, or part of the class that the framework needs added to field type. Examples:

```
large_text('foo');      // Bootstrap 2
span3_select('bar'); // Bootstrap 2
three_text('baz');     // Foundation 3
```

This doesn't work for the current versions of those frameworks as they now use grid column classes such as large-6 (Foundation) and col-lg-6 (Bootstrap). Note those hyphens, you can't put them into PHP function names. So as a minimum we need to get rid of those hyphens and use, for example: large6 and collg6 respectively or just lg6 for Bootstrap 3 and expand the classes in the relevant framework classes.

But I propose that we go further and introduce a Former vocabulary for field widths. So that instead of needing to inject framework-specific classes or variants, users can use for example large6_text('foo') and have the framework class for Bootstrap 3 recognize that this means add a class of "col-lg-6", while that for Foundation 4 knows to add "large-6 columns". This would enable users to switch more easily between frameworks furthering the goal of making it framework agnostic.

Allowance could still be made in each framework class to support classes such as Bootstrap 2's span widths, for both backward compatibility and those users locked into a specific Framework version who don't really care about switching but want the precision of framework-specific features.

As an aside, when pre-pending lg and sm without a col or size integer in Bootstrap 3, the equivalent of prepending large and small in Bootstrap 2, this now changes the height rather than the width of the field. That could cause some confusion for people upgrading to version 3, but isn't as odd as it sounds, since these settings for buttons already affected their height more than their width.

**Comment by jp7carlos** [comment]
@jijoel 
Found it in another issue:

Former::text('foo')->onGroupAddClass('col-sm-2')

**Comment by crmitchelmore** [comment]
Doesn't seem to work.

This style seems like it would be compatible with all the frameworks
 ````
Former::text('foo')->small(2)->large(8)->medium(4);

**Comment by TommyC81** [comment]
Please update this, the fixed settings just doesn't work. I'm more than happy to specify the exact classes I want added, just need a suitable generic function for it.

**Comment by claar** [comment]
Here is a workaround for this issue. It's not pretty and fluent, but it works. PRs welcome for a better solution.

#### To set label width per-form:

```php
<?php Former::setOption('TwitterBootstrap3.labelWidths', array('large' => 2, 'small' => 3)) ?>
<?= Former::horizontal_open() ?>
```

#### To set label width globally:

```php
// In your published former config file
'TwitterBootstrap3' => [
    'labelWidths' => array('large' => 2, 'small' => 3),
],
```

**Comment by bart** [comment]
@claar Your workaround doesn't work, because I'm not able to add multiple fields into one row like this:

```
<div class="form-group">
        <label for="postcode" class="col-sm-2 control-label">Postcode / City</label>
        <div class="col-sm-3">
            <input type="text" class="form-control" id="postcode" name="postcode" />
        </div>
        <div class="col-sm-7">
            <input type="text" class="form-control" name="city" />
        </div>
    </div>
```

Any solution for this?

**Comment by claar** [comment]
@bart Yeah, Former can't help you there currently. That's a separate issue, though; handling group errors is its own mess.
