### ISSUE TITLE
[L4] Populator from Array and Relationships

### ISSUE THREAD

**Issue by henriquebim** [formers/former#238]
Hello,

I'm having some problems with the populator.
I started populating from Eloquent instance, but later needed a Presenter, so I included auto-presenter (https://github.com/ShawnMcCool/laravel-auto-presenter), after including it, populating stopped working. I figured I should populate from database and not from presenter, so I used ->toArray() in Eloquent's model.

Things got populated, but not relationships (I'm currently using address[street], but tried using address.street and got the same result).

Digging in the source code of Populator, I found this lines (Former/Populator.php:39~41):
```PHP
if (is_array($this->items)) {
      return parent::get($field, $fallback);
}
```

It seems it try to get 
```PHP
$items['address[street]']; // (or items['address.street'])
```

instead of 
```PHP
$items['address']['street']
```

The quickfix I found is removing the above 3 lines.

Any thoughts on this? :)

**Comment by claar** [comment]
Closing old inactive issues to make project maintainable.
