### ISSUE TITLE
Exception when a textarea fields has [ in its name attribute

### ISSUE THREAD

**Issue by sdebacker** [formers/former#243]
this exception is thrown : Method Former\Form\Fields\Textarea::__toString() must not throw an exception.

Example : {{ Former::textarea('en[summary]')->label('summary'); }} 
More info here : https://github.com/Anahkiasen/former/commit/f6411aaa3185fe2ba842731f887fc9cb5a36e4ef#commitcomment-4611218

**Comment by mashpie** [comment]
same on hidden fields, @see #478

**Comment by claar** [comment]
I can no longer reproduce this -- appears to have been fixed some time ago.
