### ISSUE TITLE
question: security and xss on inputs

### ISSUE THREAD

**Issue by mikhailkozlov** [formers/former#279]
Is there a good way to prevent xss on following code:

```
Former::hidden('redirect', Input::get('redirect', '/'))
```
hitting this page with 
```
?redirect=%22%3E%3Cimg%20src=x%20onerror=prompt%28"Why?"%29%3E 
```
will create prompt popup on the page. 

Doing something like 

```
Former::hidden('redirect', e(Input::get('redirect', '/')))
```
does nothing as I presume Former does something too and it converts code into html again.

Issue mainly exists in FF 

Any advice? 

Edit:

Did a bit more digging, looks like

```
  private function repopulate($fallback = null)
```

Catches data from request and puts it into form. Something like code bellow should fix the issue:
```
  /**
   * Use values stored in Former to populate the current field
   */
  private function repopulate($fallback = null)
  {
    // Get values from POST, populated, and manually set value
    $post      = $this->app['former']->getPost($this->name);
    $populator = $this->form ? $this->form->getPopulator() : $this->app['former.populator'];
    $populate  = $populator->get($this->name);

    // Assign a priority to each
    if (!is_null($post)) {
      return e($post);
    }
    if (!is_null($populate)) {
      return $populate;
    }

    return $fallback ?: $this->value;
  }
```

**Comment by claar** [comment]
Unfortunately, I don't see a way to do this that wouldn't break existing code. I recommend not using Former::hidden() in this case an using raw HTML to write out that hidden variable.
