### ISSUE TITLE
put sr-only class on labels when using inline form on bootstrap

### ISSUE THREAD

**Issue by Daskul** [formers/former#284]
make labels on form controls to have sr-only class when using inline form on bootstrap or provide option to disable auto append of label.

**Comment by claar** [comment]
You can use `->raw()` to disable auto-appending of the label.

**Comment by tranba** [comment]
@jaimesangcap , @claar I think we have this feature:
https://github.com/formers/former/commit/775e842ff645b5807b96dddc783286d4a744d74b#diff-3056a3dcfef196352ada9663ef91fb49

**Comment by claar** [comment]
@tranba Nice, thanks for the pointer!
