### ISSUE TITLE
Former::open() doesn't accept array values for image upload

### ISSUE THREAD

**Issue by DharaBhut** [formers/former#292]
Hello,

I m trying to upload image using former, but when I give array like

{{ Former::open($url,array('files'=>true))->addClass('col-md-12 main_form')->method($method); }}

It gives me error 
         strtoupper() expects parameter 1 to be string, array given

Thanks.

**Comment by pandaboy** [comment]
@Anahkiasen I think you should update the documentation to reflect that the open method doesn't exactly match the `Form::open` method in the Laravel 4.2 docs. Had to find this issue to see how to assign the urls. You can't do this for example:
```php
Former::open(['route' => 'posts.store', 'class' => 'formerly-known-as-prince'])
```
Even though it's a valid creation method for Laravel 4.2
