### ISSUE TITLE
Labels not displayed when views are inherited 

### ISSUE THREAD

**Issue by dallasmatthews** [formers/former#293]
I love Former.

It does everything I want it to, and lots of things I didn't even know I wanted (hello datalists!).

I'm frustrated at an issue that may well be my fault.

I have a child view that extends another main (parent) view, which, in turn extends a layout. (This is multi-tenancy app so I over-ride the default views with tenant specific views).

- If I define a label in the [parent view](https://gist.github.com/dallasmatthews/9910692), then it shows fine.
- If I define a label in the [child view](https://gist.github.com/dallasmatthews/9910726) view, then everything renders as it should except it ignores anythign I have defined for the label.

e.g. If I put this line in the parent view, all is good. If I put the line in a section in the child view (that extends the parent view), I get no label*.

    {{ Former::select('_order_product[product_id][]')
    ->class('form-control input')
    ->options($record->productList())
    ->label('new label') }}

Any ideas where I might be going wrong?

Thanks for your advice. I didn't post lines of code here to keep it tidy, but you can see my [child view](https://gist.github.com/dallasmatthews/9910726) and [parent view](https://gist.github.com/dallasmatthews/9910692) in a gist, and please let me know if you need more info about how I have set things up.

*If I set the `'automatic_label'   => false,` in config.php, then the child view still ignores any label I have set and shows the computed label.

**Comment by claar** [comment]
To be honest, this doesn't sound like a Former problem. If you can create a simple test-case in a single view showing the problem, I'm happy to look into it.

**Comment by dallasmatthews** [comment]
You were quite right. I'm an idiot! (View inheritance)

Thanks for the reply though!
