### ISSUE TITLE
Support jQuery Validator?

### ISSUE THREAD

**Issue by spib** [formers/former#30]
Hi,

Great work on this bundle. I wondered if you had considered supporting a different client side validation framework? For example, to support jQuery Validate (https://github.com/jzaefferer/jquery-validation) you would only need to make a minor change to the Filed::addRules() method

  $this->attributes['data-validations'] = implode('|', array_keys($rules));

Putting this in would add the necessary 'data-validations' attribute to the element which should support most of the basic rules

Thanks

James

**Comment by claar** [comment]
Closing old inactive issues to make project maintainable.
