### ISSUE TITLE
State setting ignored

### ISSUE THREAD

**Issue by eComEvo** [formers/former#316]
I'm trying to set the `state()` of a field to 'error' when there is an error.

To do this, I'm doing:

    {{ Former::text('name', 'items/table.name')->state('error') }}

However, this does nothing.

Is this a bug or am I doing something wrong?

I'm trying to get an appearance similar to the bootstrap validation states on error:
http://getbootstrap.com/css/#forms-control-validation

**Comment by claar** [comment]
For Bootstrap3, you'd use `{{ Former::text('name')->onGroupAddClass('has-error') }}`
