### ISSUE TITLE
Post form through Ajax looses validation notifications

### ISSUE THREAD

**Issue by reneweteling** [formers/former#317]
Hey Maxime,

Thanks for the great plugin btw! using it allot! I came about somthing weird. I have a form and when you submit it and it doesnt validat i use 
```

        $v = Validator::make($input, $rules );
        if( $v->fails() ){
            // falue messages for the form
            Former::withErrors($v);
            // falue messages for the base temaplate ( alerts etc )
            $this->layout->content = View::make( 'signup.signup-step-1' )->with('open', true);
```
all is well, only when i post the form using Ajax, on the return data the error notifications are not visible in the form. The $v does has the errors, when i insert a dd($this->errors) on Former.php:271 i can see the errors, so i know former knows the errors. Only they are not displayd.

A little hack is use to overcome this weird behaviour is in the template just before the form starts 
````
<?php
                if( $v ){
                    // weird hack to get the errors when posting the form with ajax
                    Former::withErrors($v);
                }
            ?>
            {{ Former::vertical_open()->addClass('form-signup-signin') }}
````
This seems to work in the Ajax environment, only i really don't know why

Thanks!!

**Comment by claar** [comment]
I believe this has to do with `Input::old()` not being set as expected due to using Ajax instead of POST. Former expects to be showing a page after a redirect, but with Ajax, you're showing the form on the same page as the POST I assume. You'll need to use your workaround, I believe.
