### ISSUE TITLE
labels not showing when using "Nude"

### ISSUE THREAD

**Issue by icylace** [formers/former#320]
`Former::text('given_name')->label('First Name: ')`

will show the label as expected but using:

```
Former::framework('Nude');
Former::text('given_name')->label('First Name: ')
```

will not show the label.

**Comment by claar** [comment]
I can't reproduce this. Please comment if it's still a problem.

**Comment by KrisGHE** [comment]
I'm seeing this problem as well.

This doesn't show a label:

<?php Former::framework('Nude'); ?>
<?= Former::open()->method('POST'); ?>
<?= Former::text('name')->label('name'); ?>
<?= Former::close() ?>

When I put the text field outside of the form, it does show the label:

<?php Former::framework('Nude'); ?>
<?= Former::open()->method('POST'); ?>
<?= Former::close() ?>
<?= Former::text('name')->label('name'); ?>

Using the default framework will show the label in either case:

<?= Former::open()->method('POST'); ?>
<?= Former::text('name')->label('name'); ?>
<?= Former::close() ?>
