### ISSUE TITLE
ID can contain spaces and other non-alpha characters

### ISSUE THREAD

**Issue by that0n3guy** [formers/former#321]
If I do something simple like:

             {{ Former::text('Current Annual Income:') }}

I get an output of something like: 

    <input class="form-control" id="Current Annual Income:" type="text" name="Current Annual Income:" >

There are several problems with this.  There are spaces in the ID, and it puts the colon in there as well.  

Per HTML4 standards: ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods ("."). Note, HTML5 allows for name to be anything.

Its easy to get around this by adding a id() method... but that shouldn't be required all the time.

**Comment by claar** [comment]
Same as #451.
