### ISSUE TITLE
problem with errors message when passing Former to array and then view it.

### ISSUE THREAD

**Issue by yuomtheara** [formers/former#323]
I want to pass Former to array and then view it like
```php
// in view
$form = array(
Former::text(),
Former::text(),
Former::text(),
);

foreach($form as $value){
    echo $value.'<br>';
}
```
It have problem when check validator->fails(), by return duplicated of errors message in the text box nearly.

**Comment by claar** [comment]
If that's your full code, then I would expect the problem, as you didn't pass a name to `text()`. If your code is different, please post a more full snippet. Thanks!
