### ISSUE TITLE
Removing <div class="col-lg-10 col-sm-8"> from generating

### ISSUE THREAD

**Issue by vivekiran** [formers/former#326]
Can i remove <div class=col-lg-10 col-sm-8> tag before forming the form?

Code:
Former::text()->attributes($fieldAttributeResults)->prepend('<i class="fa fa-key"></i>');

Result:
<div class="form-group"><div class="col-lg-10 col-sm-8"><div class="input-group"><span class="input-group-addon"><i class="fa fa-key"></i></span><input type="text" inline="test" value="" placeholder="Username" name="username" id="username" class="form-control"></div></div></div>

**Comment by claar** [comment]
Does adding `->raw()` do what you want?
