### ISSUE TITLE
Does forceValue override POST data?

### ISSUE THREAD

**Issue by gmarlett** [formers/former#333]
Does forceValue override POST data?  The documentation makes it unclear:

All form classes encounter a problem at one point : what kind of data takes precedence over what kind ? To populate your field, Former set the following priorities to found values :

POST data takes precedence over everything – if a user just typed something in a field, chances are this is what they want to see in it next time
Then comes data set via the ->forceValue() method – it's a special branch of ->value() created to force a value in a field no matter what happens
Then any values set via Former::populate() – that means that if you're editing something or are repopulating with some value, it can be overwritten with forceValue
Finally the classic ->value() gets the least priority – it is created for minimum and default field values and thus gets overwritten by population and POST data

**Comment by claar** [comment]
Sorry, the docs are quite out of date and overly sparse. And in this case, plain wrong.

To answer your question directly, yes -- `->forceValue()` overrides POST data. I've fixed the documentation.

The real precedence is:
* `->forceValue()`
* value from `$_POST`
* value from `->populate()` (such as your model's value)
* `->value()`

Interestingly, I don't think this was supposed to be the precedence originally, I think `$_POST` was intended to override `->forceValue()`, but it's too late to change it now. :)

**Comment by kutukode** [comment]
Sorry for opening this issue again.

I saw in the docs, there is a method like this:

* Then any values set via `Former::text()->populate()`, so you can override any global population on a per-element basis.

Is this still supported? I tried it but it seems not working (the field is still populated from `Former::populate()`)
