### ISSUE TITLE
Validation/errors do not work when concatenating fields

### ISSUE THREAD

**Issue by stevenmyhre** [formers/former#334]
To reproduce:

Create two fields with "required" validation attached to them, (via `->withErrors()`), and concatenate them together:

```
echo Former::text('first_name')->label('First Name')->maxlength(50)
. Former::text('last_name')->label('Last Name')->maxlength(50)
```

If I then, say, don't fill in both these fields and hit submit, both fields will show a help message of "The last name field is required".  It's using the last field that was in the concatenation.

Looking through the code, it looks like the getErrors() function is *stateful*...  It relies on a field within the $app variable:

```
$this->app['former.field']->getName();
```

I'd argue this shouldn't rely on these methods being called in the correct order

**Comment by claar** [comment]
I agree with you 100%. Unfortunately, reworking that would be a large task. You can use this as a workaround:

```php
echo Former::text('first')->label('First Name')->maxlength(50)->wrapAndRender()
. Former::text('last')->label('Last Name')->maxlength(50)->wrapAndRender()
```
