### ISSUE TITLE
Checkboxes genereted on form submit with errors

### ISSUE THREAD

**Issue by reneweteling** [formers/former#340]
I have the weirdest thing, i have a form with some checkboxes, when i post and the record is updated / created there is no problem but when the form fails validation and is returned to the client all the checkboxes ( that silently have been created by the 'push_checkboxes' config ) are added to the existing one's giving me this weird output

![image](https://cloud.githubusercontent.com/assets/3830933/3373251/03b3d0e4-fbb2-11e3-8325-58ebc2e4e19f.png)

if you set the 'push_checkboxes' to false, the problem is gone ( creating one of not knowing what you are posting ) 

any idea? love to hear it! Thanks!

**Comment by claar** [comment]
Closing old issues.
