### ISSUE TITLE
bug in Former __call ? calling wrong framework

### ISSUE THREAD

**Issue by dwenaus** [formers/former#355]
When calling Former::actions()->large_submit('Submit') using Foundation4 the Twitter framework is actually called.

i'm not sure this is a proper fix, so I'm not submitting a pull request. but on this line:
https://github.com/Anahkiasen/former/blob/master/src/Former/Former.php#L141

the logic should maybe change to 
`$framework = isset($this->app['former.framework']) ? $this->app['former.framework'] : $this->app['former.form.framework'];`

**Comment by claar** [comment]
Try setting the framework in the config file.
