### ISSUE TITLE
[L4] Problem with checkbox markup not matching Bootstrap 3

### ISSUE THREAD

**Issue by benfreke** [formers/former#356]
Hi

I'm using Former (3.5.0) with TwigBridge, so my code examples may not make much sense. Basically though, this is the output I have:

    {{ Former.checkbox('roles').label('User Roles').checkboxes( user_model.getAllRolesForCheckbox() ).check(user_model.getUserRolesForCheckbox()) }}

That outputs the following HTML

    <div class="form-group">
        <label for="roles" class="control-label">User Roles</label>
    
        <div>
            <label for="access[1]" class="checkbox"><input id="access[1]" name="access[1]" checked="checked" value="1" type="checkbox">Super Admin</label>
            <label for="access[2]" class="checkbox"><input id="access[2]" name="access[2]" value="1" type="checkbox">API access</label>
            <label for="access[3]" class="checkbox"><input id="access[3]" name="access[3]" value="1" type="checkbox">User access</label>
            <label for="access[4]" class="checkbox"><input id="access[4]" name="access[4]" value="1" type="checkbox">Licence access</label>
            <label for="access[5]" class="checkbox"><input id="access[5]" name="access[5]" value="1" type="checkbox">ITR access</label>
        </div>
    </div>

So that's got 2 bugs with it.

1. The initial label's attribute "for" is always wrong, as there is never an element with that id
2. According to Bootstrap (I'm using 3.2.0, but I checked back to 3.0.3), each label / input pair should be wrapped in a div with the class checkbox. As it isn't, the styling on my site is thrown out and the checkboxes are outside the content area. There is a padding of 20px on .checkbox label that BS3 relies on, which isn't being applied in this code. Unless it's inline checkboxes, in which case there is no surrounding div tag? 

Lastly, it would be very handy knowing which version of Bootstrap the Former output outputs. I've updated the config `framework` value to TwitterBootstrap3, but which 3.x version is it supporting/passes tests for?

**Comment by claar** [comment]
Closing old issues -- please comment if you're still having problems.
