### ISSUE TITLE
Error with Ardent relationship: Object of class Illuminate\Support\MessageBag could not be converted to int

### ISSUE THREAD

**Issue by lfbittencourt** [formers/former#357]
I'm facing an issue using Former with Ardent models. Here is the big picture that throws the error:

- I have an Ardent model (`Project`) that belongs to another Ardent model (`Customer`);
- In an edit controller, I populate my form with `Former::populate($project);`. My markup to this combo is `{{ Former::select('customer')->options(Customer::orderBy('name')->lists('name', 'id')) }}`;
- Then, in the `Former\Form\Fields\Select` excerpt below (lines 93-100)...

```php
$this->value = (array) $this->value;

// Mark selected values as selected
if ($this->hasChildren() and !empty($this->value)) {
  foreach ($this->value as $value) {
    $this->selectValue($value);
  }
}
```

- ... `$this->value` holds all `Project` properties in array form, including this one from Ardent:

```php
/**
 * The message bag instance containing validation error messages
 *
 * @var \Illuminate\Support\MessageBag
 */
public $validationErrors;
```

- Then, in `selectValue` method, `$child->getAttribute('value') == $value` comparison throws the error, as Former is trying to compare an integer and a `MessageBag` object.

So, maybe we have an issue here. What I'm wondering is: why loop through **all** model properties?

**Edit**: maybe this workaround can do the trick:

```php
if ($this->value instanceof ArrayableInterface) {
    $this->value = $this->value->toArray();
} else {
    $this->value = (array) $this->value;
}
```

**Comment by claar** [comment]
Closing old issues -- please comment if you're still having problems.
