### ISSUE TITLE
Checkboxes & Array Names

### ISSUE THREAD

**Issue by williamvicary** [formers/former#364]
I'm trying to build a form that allows multiple checkboxes and returns selected values to the controller as an array, so inputs similar to this:

```
<input id="accounts" type="checkbox" name="accounts[]" value="X">
<input id="accounts" type="checkbox" name="accounts[]" value="Y">
<input id="accounts" type="checkbox" name="accounts[]" value="Z">
```

And then loop over the results similar to this:

```
foreach ($accounts as $account)
{
   [...]
}
```

I don't seem to be able to do this with Former, I've tried a few combinations and performed a few searches but nada, any tips or is this to be expected (I appreciate this is an edge case, but it can't be THAT uncommon!)

Edit: This stackoverflow URL describes nicely what I'm attempting to do: http://stackoverflow.com/questions/18421988/getting-checkbox-values-on-submit

**Comment by stefanius** [comment]
Is this issue stil open? I have the exact same problem.

**Comment by claar** [comment]
@stefanius What is the code you're using?

**Comment by thijskok** [comment]
We're running into the same problem. This is the code we are using:

```
{!!
	Former::checkboxes("permissions[]")
   			->checkboxes(
          	$permissions->keyBy('name')
                         ->map(function($p) {
             	            return ['name' => 'permissions['.$p->id.']', 'value' => $p->id]; 
             	         })
                         ->toArray()
                    )
            ->help('roles.help.permissions')
            ->label('roles.fields.permissions')
!!}
```

The form is populated by a simple `Former::populate($role)` preceeding it.

The actual exception that is thrown is caused by comparing an integer to a collection in **Checkable.php** (515):

```
if (!is_null($post) and $post !== $this->app['former']->getOption('unchecked_value')) {
	$isChecked = ($post == $value);
} elseif (!is_null($static)) {
	$isChecked = ($static == $value); // $static is a collection, $value an integer
} else {
	$isChecked = $checked;
}
```

The $static variable is a collection, because no match is found in the preceeding lines in **Checkable.php**:

```
if ($static instanceof Collection) {
	// If the repopulate value is a collection, search for an item matching the $groupIndex
	foreach ($static as $staticItem) {
		$staticItemValue = method_exists($staticItem, 'getKey') ? $staticItem->getKey() : $staticItem;
		if ($staticItemValue == $groupIndex) { // this one never matches, $static remains a collection
			$static = $staticItemValue;
			break;
		}
	}

} else if (isset($static[$groupIndex])) {
	$static = $static[$groupIndex];
}
```

I would argue that either $static should become an integer in every case or a  the integer comparison should be protected by doing another type check like ```(!($static instanceof Collection) && $static == $value)```.

**Comment by claar** [comment]
I don't have time to dive into this deeply at the moment, but have you tried `Former::checkboxes("permissions")` instead of `Former::checkboxes("permissions[]")` ?

**Comment by thijskok** [comment]
I just tried it. Leaving out the brackets will cause the populate function to skip the permission checkboxes altogether. It might have something to do with _getGroupIndexFromItem_ (called a few lines earlier), which expects brackets to be there:

```
public static function getGroupIndexFromItem($item)
{
	$groupIndex = preg_replace('/^.*?\[(.*)\]$/', '$1', $item['name']);
```

We are currently using our own fork of Former using the solution mentioned above, which is working fine. I could submit a PR for this, if desired.

**Comment by claar** [comment]
PRs very welcome. Include a test to show what the PR fixes if possible. Thanks!

**Comment by claar** [comment]
Closing old issues -- it's possible to repopulate checkboxes and examples are in our documentation. If further assistance is needed please open a new issue.
