### ISSUE TITLE
Does not fill in on validation errors

### ISSUE THREAD

**Issue by TheTechnoMan** [formers/former#369]
I have the problem that the data does not get automatically filled back in if a validation error occured. The input's are completely empty then, so it also overwrites the default value which has been set with `value()`.

I use this code to redirect back:

`return Redirect::back()->withErrors($package->errors())->withInput();`

Any idea what the problem could be?

Thank you very much for any help.

**Comment by claar** [comment]
I don't use Twig, sorry, and it's unclear if this is a Former problem or a Twig problem. Please post more information if you still need help. Thanks!
