### ISSUE TITLE
state() method does not change error message class

### ISSUE THREAD

**Issue by eComEvo** [formers/former#370]
I am trying to change the 'state' of an element's error message depending on if it has errors. When the form reloads with errors, Former automatically shows the error message inline, but doesn't show that message with an error state in the blade template using this code:

    {{ Former::text($s['name'], $s['display_name'])->forceValue($s['value'])->setAttributes($s['attr']) }}

I tried forcing this when an error is detected, but the state still doesn't set for the message:

    {{ Former::text($s['name'], $s['display_name'])->forceValue($s['value'])->setAttributes($s['attr'])->state($errors->has($s['name']) ? 'error' : '') }}

Even if I hardcode the state to all fields, it only affects the input field itself, not the inline help:

    {{ Former::text($s['name'], $s['display_name'])->forceValue($s['value'])->setAttributes($s['attr'])->state('error') }}

**Comment by claar** [comment]
Make sure you're calling `Former::open()` before your inputs; Former should be automatically setting the error state, so I'm not sure what's wrong here. Please provide more information if you're still having problems.
