### ISSUE TITLE
form horizontal doesn't work

### ISSUE THREAD

**Issue by mnewmedia** [formers/former#383]
Hi if i make `Fomer::horizontal_open` it adds the class `form-horizontal` but i think that's not enough.
Don't i also have to add the classes `col-sm-` to the label and the input? how can i do this with former?

shouldn't it render like this:
```html
<form class="form-horizontal" role="form">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>
```

**Comment by claar** [comment]
Make sure you've set the TwitterBootstrap3 framework in your config file.
