### ISSUE TITLE
Inline error messages not displayed when input element names are arrays

### ISSUE THREAD

**Issue by eComEvo** [formers/former#384]
If I have the following Blade form element:

```
{{ Former::text('form_group_name[named_key]', 'Some Field Name') }}
```

Then if I return a message bag (`Illuminate\Support\MessageBag`) with the error key `form_group_name[named_key]` then Former will not display the error help element as it would if I did something like `form_group_name_named_key` as the error key in the message bag.

Is this a bug? Or is there some way to get around this while still maintaining the convenience of an array structure in my form?

**Comment by claar** [comment]
Sounds like a bug. Former has some remaining issues with array fields.

**Comment by claar** [comment]
I have tested this manually and with an automated test `NudeFrameworkTest::testCanDisplayNestedErrorMessages()` -- nested error messages work correctly.

Note that in your message bag, you should use dotted notation for your keys, such as `form_group_name.named_key`, which is the notation Laravel uses out of the box for such keys.
