### ISSUE TITLE
Raw values for fields

### ISSUE THREAD

**Issue by rseyferth** [formers/former#386]
This is more of a feature-request/suggestion than an issue, but it would be nice to have an option within Former to use raw values in fields. For example when you want to include a Former form in a JS-template, and have the template set the value, you would want something like:

    {{Former::text('name')->value('<%= user.name %>')}}

But in this case the < and > will be html encoded by Traits/FormerObject:101. Using Laravel's `DB::raw()` around the value works, but it would be nice if that functionality would be in Former itself. Something like `Former::raw()`, which wraps the string in a simple class with a __toString() method, so it is not encoded. And perhaps a shortcut like `$field->rawValue('...')`.

**Comment by claar** [comment]
I'd accept a PR for `->rawValue()`, sounds useful.
