### ISSUE TITLE
Fix example for non-view helper

### ISSUE THREAD

**Issue by roosterjm2k2** [formers/former#404]
In your example for non-view:

```php
$form = Former::open()->method('GET');
    $form .= Former::text('name')->required();
$form .= Former::close();
```

That will never wrap form elements in control groups.  You set the Form::$opened in the __toString method on the Form class - so when you call Former::open() directly and assign to something, if you aren't appending it as a string, it will never set $opened, and hasInstanceOpened() will never be true in the wrapAndRender method, therefore never wrapping the elements.  No code change is needed to fix, just update the wiki/readme to make sure its a string (and maybe add a comment in there):

```php
// Be sure to cast to string
$form = (string)Former::open()->method('GET');
    $form .= Former::text('name')->required();
$form .= Former::close();
```

**Comment by claar** [comment]
This change was made to the docs sometime ago.
