### ISSUE TITLE
Documentation error - setting which checkboxes in group are checked

### ISSUE THREAD

**Issue by bschooly** [formers/former#405]
This doc snippet below appears to be wrong.  The array keys should be the label names, no underscore and no number. 

// Set which checkables are checked or not in one move
Former::checkboxes('level')
  ->checkboxes(0, 1, 2)
  ->check(array('level_0' => true, 'level_1' => false, 'level_2' => true))

This is from http://anahkiasen.github.io/former/

**Comment by claar** [comment]
Dupe of #400
