### ISSUE TITLE
Icon in submit buttons

### ISSUE THREAD

**Issue by SilverPaladin** [formers/former#406]
There doesn't seem to be a way to add an icon to a submit button. Have I missed something in the docs?

I tried `Former::actions()->sm_success_submit('Re-Open',['class'=>'btn-no-rc', 'name'=>'close'])
		->prepend('<i class="fa fa-print"></i>')`
but this just add an attribute to the containing div called prepend with the value of icon.

**Comment by 321zeno** [comment]
`Former::button('button')->icon('iconClass')` works for me but I can't find a easy way to get it working with `actions()`

**Comment by claar** [comment]
```php
Former::actions(
  Former::primary_button('submit')->icon('ok'), 
  Former::default_reset('Reset')
)
```
works for me.

**Comment by bahjaat** [comment]
Ended up with:
<pre>
Former::actions(
  Former::primary_button('submit')->icon('ok')->type('submit'), 
  Former::default_reset('Reset')
)
</pre>

**Comment by claar** [comment]
Awesome, thanks for posting the solution, @bahjaat.
