### ISSUE TITLE
Add selected options for Select and fromQuery

### ISSUE THREAD

**Issue by gilbert1995** [formers/former#410]
In Fields/Select.php
Just update like this

  /**
   * Use the results from a Fluent/Eloquent query as options
   *
   * @param  array  $results  An array of Eloquent models
   * @param  string $value    The attribute to use as text
   * @param  string $key      The attribute to use as value
   * @param  string $selected The default selected element
   */
  public function fromQuery($results, $value = null, $key = null, $selected = null)
  {
    $this->options(Helpers::queryToArray($results, $value, $key), $selected);

    return $this;
  }

**Comment by claar** [comment]
Closing old issues. PRs welcome!
