### ISSUE TITLE
Populator not working with Presenter

### ISSUE THREAD

**Issue by KuenzelIT** [formers/former#411]
Hey,
can someone explain to me the "getAttributeFromModel" method in "former / src / Former / Populator.php". Why isn't there just the following code, which works with my Presenter.
```
return isset($model->$attribute) ? $model->$attribute : $fallback;
```

Unfortunately the current method doesn't work with "presenter" (https://github.com/robclancy/presenter), because it's not an instance of "Model" and doesn't work as an array.

Thanks!

**Comment by claar** [comment]
Closing old issues. Please comment if still needed.
