### ISSUE TITLE
Some fields populate with a series of commas

### ISSUE THREAD

**Issue by Forbin** [formers/former#414]
I cannot see a cause, the naming is consistent, but some fields are filled with 5 to 9 commas. 
![commas](https://cloud.githubusercontent.com/assets/294007/5306562/9ddcd770-7bc2-11e4-8214-2afdb88a8612.png)

In the data there are no values for password etc. Other parts of the form are working. The only common aspect is that these are nested values.

Portion of fields:
        {{ Former::text('users[primary][first_name]')
			    ->placeholder('First Name')
			    ->required()
		    }}
	        {{ Former::text('users[primary][last_name]')
			    ->placeholder('Last Name')
			    ->required()
		    }}
	        <br />
	        {{ Former::text('users[primary][email]')
			    ->placeholder('Email')
			    ->required()
		    }}
	        {{ Former::text('users[primary][password]')
			    ->placeholder('Password')
			    ->required()
		    }}
	        {{ Former::text('users[primary][password_confirmation]')
			    ->placeholder('Password Confirm')
			    ->required()
		    }}

**Comment by d-lamers** [comment]
For me this always happens when using input arrays like you are
Former::text('users[primary][first_name]')
