### ISSUE TITLE
Multiple file inputs with 

### ISSUE THREAD

**Issue by barryvdh** [formers/former#415]
If you create multiple file input files, and the first has a max size in the validation rules, a hidden 'MAX_FILE_SIZE' field is added. But then this field also applies to the rest of the input files. I don't think that is the wanted behaviour..

**Comment by claar** [comment]
Thanks Barry -- it appears this bug got fixed some time in the last 2.5 years -- I can't reproduce it any longer. I've added tests to the test suite to verify it can't regress.
