### ISSUE TITLE
Regex not rendering properly

### ISSUE THREAD

**Issue by thisistouhid** [formers/former#428]
Got a problem with regex for live validation.
I am using this regex:

```
'number'    =>  'regex:[\d{3,10}]|required',
```

as rules for live validation. The rendered html is 

```
<input pattern="\d{" required="true" ..................">
```

which should be

```
<input pattern="\d{3,10}" required="true" ..................">
```

But this works:

```
{{ Former::text("number")
    ->pattern('\d{3,10}')
}}
```

what am i missing here?

**Comment by coednaked** [comment]
I found the problem in Former.php line 304 
I replaced with this to solve the problem 
				if (($colon = strpos($rule, ':')) !== false) {
					$rulename = substr($rule, 0, $colon) ;
					if($rulename !== 'regex'){
						$parameters = str_getcsv(substr($rule, $colon + 1));
					}else{
						// reset parameters array
						$parameters = [];
						// Assign the regex as intended 
						$parameters[0] = substr($rule, $colon + 1);
					}
				}

I think the problem is the str_getcsv  is splitting the regex on ","

**Comment by dynosure** [comment]
@coednaked thx for pointing out the position of the problem. As it uses `str_getcsv` which means you can add a `"` arround the regex to prevent the splitting:

Use `'number'    =>  ['required', 'match:"/\d{3,10}/"']` instead

**Comment by KuenzelIT** [comment]
Had the same problem, thanks to @coednaked for pointing it out. Is this going to be fixed? I think array support is also missing in this method?
