### ISSUE TITLE
Laravel 5

### ISSUE THREAD

**Issue by CedNet** [formers/former#433]
Hi, are you going to support Laravel 5? I've been using your package a lot and it's great. About to start a new project that will begin with Laravel 5 and I can't get it to work.

It throws an error: FatalErrorException in FormerServiceProvider.php line 147:
Call to undefined method Illuminate\Config\Repository::package()

Or maybe you will wait until it's officially released?

**Comment by Anahkiasen** [comment]
There is no official documentation for packages for Laravel 5 yet so not much I can do about that until then unfortunately

**Comment by CedNet** [comment]
Alright, understandable. Hope it's released soon with all the documention you need to support Laravel 5. :)

**Comment by stevenmyhre** [comment]
http://laravel.com/docs/master/packages

**Comment by claar** [comment]
I've added a laravel5 branch at https://github.com/Anahkiasen/former/commits/laravel5

Tests are passing, and I rendered a few fields, but I've done minimal testing otherwise. Feedback appreciated.

**Comment by stevenmyhre** [comment]
Great, thanks! It works, but only with the TwitterBootstrap framework.  Try setting the config 'former.framework' to `TwitterBootstrap3` and you get an error - looks like it can't find the framework specific config variables. (`labelWidths`) for me

**Comment by stevenmyhre** [comment]
Adding this to the `bindFormer` method in the FormerServiceProvider.php file seemed to work:
```
$framework = $app['config']->get('former.framework');
$this->mergeConfigFrom(__DIR__ . '/../config/'. $framework . '.php', "former.$framework");
```

**Comment by claar** [comment]
@stevenmyhre Good catch -- thanks for trying this out. Your workaround works for config-time framework choosing, but I don't believe it would work for the normal `Former::framework('TwitterBootstrap3')` functionality.

It looks like the problem is [Framework.php line 294](https://github.com/Anahkiasen/former/blob/08895e/src/Former/Traits/Framework.php#L294):

```php
	protected function getFrameworkOption($option)
	{
		return $this->app['config']->get("former.{$this->current()}.$option");
	}
```

We'll have to research the right way to do multiple config files for a package in L5.

Also it looks like the Travis CI tests failed -- tests pass locally, so I assume it's because Travis CI uses PHP 5.4.

**Comment by claar** [comment]
I've renamed the l5 branch to "4.0" per @barryvdh's [comment](https://github.com/Anahkiasen/former/commit/08895e#commitcomment-9559868), to allow using this branch via require ~4.0@dev

**Comment by barryvdh** [comment]
Ah didn't see this was already suggested, but I submitted the same fix. At least it works for now :)

**Comment by Ben-Speakman** [comment]
This breaks the ability to include an external framework file.

**Comment by Anahkiasen** [comment]
What do you mean?

**Comment by barryvdh** [comment]
Loading any framework that doesn't have a config file will probably fail, because `__DIR__ . '/../config/'. $framework . '.php'` doesn't exist.

**Comment by Ben-Speakman** [comment]
Sorry. I meant that if I pass a full namespace path to a framework file. For example
```
'framework'               => 'App\Former\SfaaFramework',
```
Then the `mergeConfigFrom()` on line 152 fails because it is looking for a file 'App\Former\SfaaFramework.php' inside the package config directory.
