### ISSUE TITLE
required() not working with Twig

### ISSUE THREAD

**Issue by InerciaCreativa** [formers/former#435]
Twig call isRequired() instead of required(), returning an empty field. The relevant code for the method search in Twig:
```php
        $call = false;
        $lcItem = strtolower($item);
        if (isset(self::$cache[$class]['methods'][$lcItem])) {
            $method = (string) $item;
        } elseif (isset(self::$cache[$class]['methods']['get'.$lcItem])) {
            $method = 'get'.$item;
        } elseif (isset(self::$cache[$class]['methods']['is'.$lcItem])) {
            $method = 'is'.$item;
        } elseif (isset(self::$cache[$class]['methods']['__call'])) {
            $method = (string) $item;
            $call = true;
        }
```
The solution is to create a required() function in Field.php.

**Comment by Anahkiasen** [comment]
Shouldn't `if (isset(self::$cache[$class]['methods'][$lcItem]))` catch `required()` ?

**Comment by InerciaCreativa** [comment]
No, because required() is not defined anywhere, that's the problem, it's calling __call('required', []).

**Comment by Anahkiasen** [comment]
What you're code in Twig? Never had that issue before AFAIR

**Comment by InerciaCreativa** [comment]
Something really simple as this it's not working:

{{ Former.text('name').maxlength(100).required() }}

If I remove .required() it just works, if I create a required() method in Field.php it just works.

**Comment by InerciaCreativa** [comment]
This is the method that I created:
```php
	public function required()
	{
		return $this->__call('required', true);
	}
```

**Comment by Anahkiasen** [comment]
But that doesn't make sense, `maxlength` isn't on Field either and it works, what if you do `.required(true)`?

**Comment by InerciaCreativa** [comment]
The problem is that there is a method in Field.php called isRequired(), and that method get called first. With maxlength() there is no problem, as there is no isMaxlength(), nor getMaxlength().

**Comment by InerciaCreativa** [comment]
Twig searchs for method(), getMethod(), isMethod() and if none is found then __call('method').

**Comment by claar** [comment]
@InerciaCreativa Is this still a problem? Like @Anahkiasen, I don't understand why you'd need to create `required()` in Field.php
