### ISSUE TITLE
"required" attribute should be rendered as valid HTML5

### ISSUE THREAD

**Issue by stevenmyhre** [formers/former#437]
The inputs, if required are rendered as:

`<input type="text" name="test" id="test" required="true">`

They should render as, to be 100% W3C compliant:

`<input type="text" name="test" id="test" required>`
or
`<input type="text" name="test" id="test" required="required"`

See the spec:

http://www.w3.org/TR/html5/forms.html#attr-input-required

**Comment by claar** [comment]
This can be closed once Anahkiasen/html-object#25 has been released.
