### ISSUE TITLE
Use Str::slug() inside a Former class?

### ISSUE THREAD

**Issue by rombat** [formers/former#441]
Hi,
I'd like to use the very convenient Laravel Str::slug() function __inside__ a Former class.
For instance, I have a Select field which options I populate with a collection. But I'd like to "slugify" the values of the options.

Something like that:
```php
{{ Former::select('marquage[]')->fromQuery($produit->marquages, 'nom' , Str::slug('nom'))}}
```
The problem is, it doesn't work. The value 'nom' is returned, instead of a "slugified" version of 'nom'.
Is there a way to do that in a convenient way?

**Comment by claar** [comment]
I suggest adding an [accessor](http://laravel.com/docs/4.2/eloquent#accessors-and-mutators) on your model, something like:

```php
public function getNomSlugAttribute($value) {
   return Str::slug('nom');
}
```

Then you could use the new `nom_slug` field in your Former calls.
