### ISSUE TITLE
using a checkbox in an input-group-addon breaks bootstrap layout

### ISSUE THREAD

**Issue by chuckreynolds** [formers/former#450]
Have this:
```php
@foreach ($groups as $key => $value)
<label>{{{ $key }}}</label>
{{ Former::group()->Class('input-group') }}
	<span class="input-group-addon">
		{{ Former::checkbox('group_check_'.$value['value'])->check(($value['checked'] == 1 ? TRUE : FALSE )) }}
	</span>
	{{ Former::input('group_title_'.$value['value'])->value($value['title']) }}
{{ Former::closeGroup() }}
@endforeach
```
Which then outputs this:
```html
<label>my label here</label>
<div class="input-group">
	<span class="input-group-addon">
		<div class="checkbox"><input id="group_check_3" type="checkbox" name="group_check_3" value="1"></div>
	</span>
	<input class="form-control" id="group_title_3" type="input" name="group_title_3">
</div>
```
Which looks like this:
![screen shot 2015-02-18 at 15 15 48](https://cloud.githubusercontent.com/assets/46185/6258850/160f52fa-b781-11e4-9a81-7552decbb08a.png)

The issue is the `<div class="checkbox">` around the input. If I remove that in chrome inspector I get what it should look like:
![screen shot 2015-02-18 at 15 17 35](https://cloud.githubusercontent.com/assets/46185/6258870/4bd01384-b781-11e4-8001-a118b1e8ef46.png)

Question is... How do I kill that extra div in the code I have above? And it works if that div doesn't use the `class="checkbox"`...  Can't tell if it's a bug when the checkbox is used as an `input-addon-group` or if I'm missing something to make Former not generate that extra div and/or checkbox class in this particular case.

Thx guys. Pretty new to Former & Laravel so. Bear with me :)

**Comment by claar** [comment]
You can remove the extra `<div class="checkbox">` by using `Former::checkbox()->raw()`.

**Comment by chuckreynolds** [comment]
Did this - no different result.
```php
{{ Former::checkbox('group_check_'.$value['value'])
	->check(($value['checked'] == 1 ? TRUE : FALSE ))
	->raw() }}
```

**Comment by chuckreynolds** [comment]
any ideas?

**Comment by claar** [comment]
Just figured this out by looking at the source code. If you add `->inline()->raw()`, it will remove the `<div class="checkbox">`.

**Comment by chuckreynolds** [comment]
yup. thank you. cheers.
