### ISSUE TITLE
Opening a form results in a "Fatal error"

### ISSUE THREAD

**Issue by tzfrs** [formers/former#454]
Hi,

I'm using composer to get this former-class.

    "require": {
            "tzfrs/curl": "1.1",
            "gilbitron/php-simplecache": "1.4.1",
            "anahkiasen/former": "3.5.3"
    }

Then, I include the autoloader of composer

`require_once __DIR__ . '/../libs/vendor/autoload.php';`

Then, I use a use statement to use the Former-Class

`use Former\Facades\Former;`

When I now want to Print a Form like this

`print Former::open()->id('editContinentForm');`

it results in a "Fatal error". Full error message:

`Fatal error: Class 'Illuminate\Config\FileLoader' not found in /Users/xx/xx/xx/libs/vendor/anahkiasen/former/src/Former/FormerServiceProvider.php on line 116`

Trace: (I hope it's good to read)

    1	0.0012	289096	{main}( )	../xx.php:0
    2	0.0521	1907248	open ( )	../xx.php:59
    3	0.0521	1907480	Illuminate\Support\Facades\Facade::__callStatic( )	../xx.php:59
    4	0.0521	1907528	Illuminate\Support\Facades\Facade::getFacadeRoot( )	../Facade.php:202
    5	0.0521	1907592	Former\Facades\Former::getFacadeAccessor( )	../Facade.php:118
    6	0.0531	1976184	Former\FormerServiceProvider::make( )	../Former.php:20
    7	0.0566	2175952	Former\FormerServiceProvider->bindFormer( )	../FormerServiceProvider.php:65
    8	0.0566	2176032	Illuminate\Container\Container->offsetGet( )	../FormerServiceProvider.php:147
    9	0.0566	2176248	Illuminate\Container\Container->make( )	../Container.php:1231
    10	0.0567	2177008	Illuminate\Container\Container->build( )	../Container.php:656
    11	0.0567	2177040	Former\FormerServiceProvider->Former\{closure}( )	../Container.php:773

**Comment by tzfrs** [comment]
Maybe interesting:

The folder /libs/vendor/illuminate/config only contains the Repository.php but not the other files listed here

http://laravel.com/api/5.0/Illuminate/Config.html

Maybe this could be a problem?

**Comment by tzfrs** [comment]
What I also found:

https://github.com/illuminate/config

The new version of the config subtree only has the Repository.php. When selecting an older version (4.2) all the files are there!

**Comment by ajarti** [comment]
It looks like you are using L5,  if so you need to use the 4.0 branch as directed in your composer.json

i.e. "anahkiasen/former": "~4.0@dev"  not  "anahkiasen/former": "3.5.3" which is what installs if you just use "composer require anahkiasen/former".

So update composer.json to ~4.0@dev and do a "composer update".

Hope that helps.
