### ISSUE TITLE
Add value to Optgroup generation

### ISSUE THREAD

**Issue by SilverPaladin** [formers/former#460]
There is a bug in IE 10 which prevents an option which shares the same index as it's parent optgroup from being submitted. 

The fix is to add a value attribute to the optgroup. Line 239 of Select.php
Change:
`$this->children[$childrenKey] = Element::create('optgroup')->label($value);`
To:
`$this->children[$childrenKey] = Element::create('optgroup')->label($value)->setAttribute('value', $value);`

**Comment by claar** [comment]
Closing old issues, please reopen with more details if still relevant.
