### ISSUE TITLE
Feature Request :: Advanced model bound forms with default resourceful controller routes

### ISSUE THREAD

**Issue by EHLOVader** [formers/former#461]
I like the way [bootstrap-form](https://github.com/dwightwatson/bootstrap-form/blob/master/src/BootstrapForm.php#L102) handled their open method. They accept a new or current instance of the object. Using that it can be determined if you are updating or creating. This also hands off the model for populating the forms fields.

I think it would be a beneficial addition and wouldn't require many changes. 

Some of the benefits include expanding the partial blade views for the form from just insides to the entire form element. There would need to be less setup logic in the controller, and I think it is a bit more intuitive than having to define these routes explicitly.

**Comment by claar** [comment]
Yeah, this could make sense -- maybe a good idea for the next version of Former, or even current if someone wants to try to tackle this in a backwards compatible manner. Closing until someone takes interest.
