### ISSUE TITLE
form fields are escaping in laravel 5

### ISSUE THREAD

**Issue by john5db** [formers/former#464]
due to the syntax change in l5 former output is escaped. and looks like html tags in output
   &lt;div class=&quot;form-group&quot;&gt;&lt;label for=&quot;name&quot; class=&quot;control-label col-lg-2 col-sm-4&quot;&gt;Name&lt;/label&gt;&lt;div class=&quot;col-lg-10 col-sm-8&quot;&gt;&lt;input class=&quot;form-control&quot; id=&quot;name&quot; type=&quot;text&quot; name=&quot;name&quot;&gt;&lt;/div&gt;&lt;/div&gt;

**Comment by claar** [comment]
This is a documentation bug, sorry. You should use `{!! Former::text('name') !!}` for Laravel 5.

I'll leave this ticket open until someone fixes the docs.
