### ISSUE TITLE
[L5] framework config values

### ISSUE THREAD

**Issue by xLink** [formers/former#474]
apparently there doesn't seem to be a way of overriding these atm, trying to do so via `Config::set()` just stops the rest of the values being applied

**Comment by claar** [comment]
To override framework config values, first run `php artisan vendor:publish` to copy the former config file to your app's `config` folder (it should be at config/former.php).

Then you can override any framework settings you like. Be sure to download the latest version of the 4.0 branch -- the framework settings are at the bottom of the config file.

**Comment by xLink** [comment]
ah there we go :D thanks!
