### ISSUE TITLE
Fatal error: Class 'Former' not found 

### ISSUE THREAD

**Issue by vladvisinescu** [formers/former#479]
I stumbled across this project and wanna use it in one of my projects.

So this is my code. What am I doing wrong ?
Note (if useful): I`m using this in Wordpress. autoload in functions.php and the rest in a template file.

>  Fatal error: Class 'Former' not found in...

```php
use Former\Facades\Former;

require 'vendor/autoload.php';

Former::horizontal_open()
  ->id('MyForm')
  ->secure()
  ->rules(['name' => 'required'])
  ->method('POST');

  Former::xlarge_text('name')
    ->class('myclass')
    ->value('Joseph')
    ->required();

  Former::textarea('comments')
    ->rows(10)->columns(20)
    ->autofocus();

  Former::actions()
    ->large_primary_submit('Submit')
    ->large_inverse_reset('Reset');

Former::close();
```

**Comment by claar** [comment]
This is either related to Wordpress or composer I think.

To test this, I just did the following, and Former worked fine:
  * `mkdir project; cd project`
  * `composer require anahkiasen/former`
  * create index.php with the following:

```php
<?php

use Former\Facades\Former;
require("vendor/autoload.php");

echo Former::open();
echo Former::text('foo');
echo Former::close();
```

Everything worked properly, so I'm not sure how to help you.

**Comment by vladvisinescu** [comment]
ok so, this works in index.php, root folder of theme, but not when I use the same code in a template file located in a subdirectory, relative to index.php.

Any ideas ?

**Comment by claar** [comment]
@vladvisinescu I wish I did, sorry! I'm afraid this doesn't appear to be a problem with Former. Let us know if you find out otherwise. Good luck!
