### ISSUE TITLE
Variable leaking out of foreach in withRules()

### ISSUE THREAD

**Issue by jp7carlos** [formers/former#480]
File https://github.com/formers/former/blob/master/src/Former/Former.php#L306
Around line 306

Variable $parameters is set inside an "if" but is not set in the next loop.

The HTML5 validation seems to work besides this. But when i use getRules() i get wrong rules.

To reproduce it use

     $form->rules(['age' => 'min:18', 'name' => 'required'])

Then call \Former::getRules('name') and you will get 

    array(1) { ["required"]=> array(1) { [0]=> string(2) "18" } }

**Comment by claar** [comment]
Oops. Nice catch.
