### ISSUE TITLE
Howto override  illuminate/translation 5.0.* requirement.

### ISSUE THREAD

**Issue by ajarti** [formers/former#481]
Hi guys,
             I am giving Laravel 5.1 a spin on the dev branch and understand it will be released shortly as Symphony's latest LTS's are out.

When I try to use former ~4.0@dev I get a dependency failure on illuminate/translation 5.0.* obviously.

My understanding that most of the underlying classes are more or less the same, is there a way to override dependencies?  

Thanks in advance.

**Comment by claar** [comment]
Thanks for the note, @ajarti. I've bumped the composer.json requirements on the 4.0 branch so 5.1 is allowed.

You may need to run `composer clear-cache` if composer doesn't notice the change.

**Comment by ajarti** [comment]
Oh nice one @claar .. kudos on a fantastic tool, it's really excellent.

**Comment by claar** [comment]
@ajarti I didn't write it, but glad it's of help!

**Comment by ajarti** [comment]
Hahaha well thanks anyway :)
