### ISSUE TITLE
Checkbox is re-checked when validation fails

### ISSUE THREAD

**Issue by stevenmyhre** [formers/former#482]
1. Open a form for editing a model that contains a boolean value (a checkbox on the form) that is initally false.
2. Edit something that will fail validation on post back - or setup your routes to go back to the original pages no matter what (as below)
3. Leave the checkbox unchecked
4. Submit the form and wait for it to redirect back to the same form, with expected the same previously entered input.

Expected: The input would be the same, and the checkbox would remain unchecked.
Observed: The checkbox is checked

Code to repro: [using laravel 5 - 4.0 branch of former]
Routes:
```
Route::get('welcome', function() {
    $model = array(
        'is_awesome' => 0,
        'name' => 'Steven'
    );
    return view('welcome')->with('model', $model);
});
Route::post('welcome', function() {
    //Input::flash();
    Log::info(var_export(Session::all(), true));
    return redirect('welcome')->withInput();
});
```

former config snippet:
```
    // Whether checkboxes should always be present in the POST data,
    // no matter if you checked them or not
    'push_checkboxes'   => true,

    // The value a checkbox will have in the POST array if unchecked
    'unchecked_value'   => 0,
```

Form:

```
{!! Former::open()->method('POST') !!}
<?php Former::populate($model) ?>
{!! Former::input('name')->label("Name") !!}
{!! Former::checkbox('is_awesome')->label('Awesome') !!}
<input type="submit" value="Submit">
{!! Former::close() !!}
```

I've tried to fix myself, but a lot of the code is confusing and there are multiple === or !== checks that I think may be the issue (comparing integer 0 to string "0")

Please help!

**Comment by claar** [comment]
Former doesn't work properly if you don't call `Former::open()` before your inputs. Let us know if that helps.

**Comment by stevenmyhre** [comment]
Wish it was that simple... no, still not working.  I've updated the example above.

**Comment by claar** [comment]
OK, I'm able to reproduce this now. For now a workaround appears to be changing the config file from 

`'unchecked_value'   => 0,` to `'unchecked_value'   => "0",`

Let me know if that helps. I'll look into a more permanent fix

**Comment by stevenmyhre** [comment]
I've tried that, and yes, it helps. But then the checkbox doesn't show up correctly on the initial load (it's checked)

**Comment by claar** [comment]
I believe you can fix that by adding `->value(1)` to your checkbox. Don't ask.

**Comment by stevenmyhre** [comment]
Yeah, won't ask, as that was an option I was considering, but I have some number of forms that I'd have to add that to to get this bug resolved - was looking for a more global solution.

**Comment by claar** [comment]
I don't have the heart to dig into this, and the checkbox system has been the bane of this project. It's very complex as you noticed, and now there are thousands of projects using it as-is, so we have to maintain strict backwards compatibility. PRs always welcome, of course.

**Comment by stevenmyhre** [comment]
Understood.  Thanks for the help thus-far.

**Comment by younes0** [comment]
using Laravel 5:
```php
        {!! Form::hidden('is_boolean', 0) !!} 
        {!! Former::checkbox('is_boolean')->value(1) !!}
```
would work without any problem
the problem is Former::checkbox doesn't add value="1"

**Comment by jp7carlos** [comment]
Post is always string 0. It is really unfortunate. Since you can't change this behavior should be good to have something documented on config/former.php like:

```php
'unchecked_value'         => 0, // You might want to change this to "0" to work with POST: https://github.com/formers/former/issues/482
```
