### ISSUE TITLE
Upgrade to Laravel 5.1 causing error in RolesServiceProvider.php line 47

### ISSUE THREAD

**Issue by Bulmer** [formers/former#483]
FatalErrorException in RolesServiceProvider.php line 47:
Call to undefined method Illuminate\View\Compilers\BladeCompiler::createMatcher()
....any idea what may be causing this? The templates seem ok and were working fine before the upgrade.  At least half of them now  result in this error.

**Comment by claar** [comment]
I'm using Laravel 5.1 with Former just fine, so I'm not sure. Can you give a little more detail? Perhaps try to reproduce it with a base 5.1 install?

**Comment by Bulmer** [comment]
Looks like I jumped to the wrong conclusion when the Blade error came up. It was actually caused by the bican/roles package. Cheers.
