### ISSUE TITLE
When push_checkboxes is set to true, Former incorrectly checks checkboxes when repopulating form using old input

### ISSUE THREAD

**Issue by TommyC81** [formers/former#484]
When the setting push_checkboxes is set to true, Former incorrectly checks the checkboxes ,regardless if it was actually checked or not, when repopulating a form using old input.

I don't think this is intentional.

Problem observed on Laravel 5.1 using latest bootstrap version.

**Comment by claar** [comment]
Try adding `->value(1)` to your checkboxes.

**Comment by asifm42** [comment]
Adding <code>->value(1)</code> to the checkboxes solved the issue for me.
