### ISSUE TITLE
[L5.1] Call to undefined method Illuminate\Config\Repository::package()

### ISSUE THREAD

**Issue by adriandmitroca** [formers/former#486]
Latest version of Laravel is missing `package()` method which Former uses for binding.

`FatalErrorException in FormerServiceProvider.php line 147:`
`Call to undefined method Illuminate\Config\Repository::package()`

Which is:
`		$app['config']->package('anahkiasen/former', __DIR__.'/../config');
`

**Comment by adriandmitroca** [comment]
My bad - I was using legacy version.

By the way - current version should be marked as master.

**Comment by ari1127** [comment]
Did this actually get fixed? or did you find a workaround?

I have a new L5.1 install and used the "composer require anahkiasen/former" install command + app.php updates, but it's still throwing this error.

**Comment by adriandmitroca** [comment]
Install this branch: https://github.com/formers/former/tree/master

**Comment by ari1127** [comment]
Yeah I did.... or at least used the composer command from the "Getting Started" link from the master. Should I not use the automated composer install?

**Comment by adriandmitroca** [comment]
Copy paste this to your composer.json file:
`"anahkiasen/former": "4.0.*@dev"`

**Comment by ari1127** [comment]
Beautiful. Thank you!

**Comment by claar** [comment]
Updates to the readme and wiki are most welcome!
