### ISSUE TITLE
Standalone

### ISSUE THREAD

**Issue by mnakalay** [formers/former#487]
Hello,

You say Former works with Laravel and other frameworks but also standalone.

How can it be used standalone? It seems to totally rely on Laravel.

Thank you

**Comment by Anahkiasen** [comment]
It relies on the Illuminate components which is different, if you try to use Former standalone it'll just bind what it needs to its internal container.

**Comment by mnakalay** [comment]
ok so nothing special to do just use it without any framework. Thank you

**Comment by Anahkiasen** [comment]
Yup, think there is some doc in the wiki but basically you just... need to use Former, it does all the rest in the background by itself
