### ISSUE TITLE
Don't put spaces in ID's

### ISSUE THREAD

**Issue by that0n3guy** [formers/former#489]
Per HTML spec, ID's shouldn't have spaces.

I run into problems with this all the time b/c developers (and myself) like to do `Former::text('First Name')` rather than  `Former::text('First_Name').label('First Name')`... which is just more typing.  We are constantly building dynamic fields and this can be a pain.

Here is the html 5 spec: http://www.w3.org/TR/2011/WD-html5-20110525/elements.html#the-id-attribute (this is also the case for html 4)

Spaces in your ID can break a lot of different javascript apps/scripts/classes/libraries.

This is related to: https://github.com/formers/former/issues/451#issuecomment-76081895

**Comment by Anahkiasen** [comment]
You shouldn't have to do `Former::text('First Name')`, Former will automatically convert the field name to a human readable label so you can do `Former::text('first_name')` and the label will be `First name` while keeping an ID of `first_name`

**Comment by that0n3guy** [comment]
I didn't know that.  That said... its still a bug since it allows ID's to have spaces.

**Comment by Lickwid** [comment]
On 4.0.x-dev this doesn't work.  Putting Former::text('First_Name') gives a label of "First_Name".

**Comment by claar** [comment]
The syntax is former is `Former::text($nameAttribute)` -- it's not within Former's scope to police what you put into $nameAttribute -- Former dutifully outputs it in HTML as requested.

This allows Former to stay flexible as the HTML spec changes, or as Former is used in ways that cannot be currently foreseen, such as to output HTML-like strings used in a javascript framework such as React/Vue/etc, that may have different rules than the HTML 5 spec (e.g. `className`, etc).
