### ISSUE TITLE
withErrors in views

### ISSUE THREAD

**Issue by rombat** [formers/former#490]
Hi,
I'm using Laravel 4.2.
I'd like to know how to have errors displayed in views on return like this:
`if($validation->fails()) {
  return Redirect::to('login')
    ->with_errors($validation);
}`
Do I have to add something in my view file or it is supposed to be included "magically" every time a form is opened with Former?
Because errors in my session are not displayed by Former, even if I haven't set the following option `Former::setOption('fetch_errors', false)`

**Comment by Anahkiasen** [comment]
Isn't it `withErrors`, not `with_errors`?

**Comment by bart** [comment]
Similiar question here:

```
{!! Former::group('ZIP') !!}
    <div class="col-sm-3">
        {!! Former::text('postcode')->placeholder('ZIP') !!}
    </div>
{!! Former::closeGroup() !!}
```

I have a dynamic form and want to add the "has-error" class to the form group in case validation for field "postcode" has been failed. Any idea?

**Comment by claar** [comment]
@bart You'll have to calculate and output the has-error class manually if you output the group manually like that (I assume you actually have multiple fields in your group as per your comment on #209). I do something similar in my project -- a bit of a pain but it works.

**Comment by bart** [comment]
Yes, that's the way I will try it. Thought there is a more eloquent way but maybe a good idea for a helper method. Thanks!
