### ISSUE TITLE
Fields not marked as error with appended items

### ISSUE THREAD

**Issue by syphernl** [formers/former#491]
We have a form with an appended button:

``` php
{!! Former::text('password')->append(Former::button()->icon('magic')->id('passwordKey')->addClass('btn-success'))->required() !!}
```

If the form fails, the field is not marked as an error. If I remove the `append` it works just fine.

**Comment by claar** [comment]
Unfortunately complex HTML doesn't work in `->append()` -- it's intended for simple text and icons. PRs appreciated, though!
