### ISSUE TITLE
When I use 5.1.11 laravel, the zh-cn translate is messy code.

### ISSUE THREAD

**Issue by wuliriki** [formers/former#496]
<?= Former::open()->method('GET')->action(route('admin.businesses.store')) ?>
                <?= Former::text('_token')->type('hidden')->value(csrf_token()) ?>
                <?= Former::text('business_name') ?>
                <?= Former::text('username')->label('model.business.business_name') ?>
                <?= Former::text('address') ?>
                <?= Former::actions()->large_primary_submit('Submit')->large_inverse_reset('Reset');?>
            <?= Former::close() ?>
![2015-10-17 14 32 33](https://cloud.githubusercontent.com/assets/8214265/10557360/ef1115e4-74db-11e5-82cd-0d10fe415573.png)

**Comment by claar** [comment]
If still needed, please post some easy code to replicate this and the raw HTML output -- I'm not overly familiar with the translation features.
