### ISSUE TITLE
Question: can i render labels as siblings of radios instead of parents

### ISSUE THREAD

**Issue by magoomby** [formers/former#497]
I'd like to render radio and checkbox labels as siblings of the input controls rather than parents so as to style the labels easily. Is this something that is easily done in the framework considering I don't want to change anything else. Do you have ANY advice on the best way to subclass your radio/checkable element so that I could render the output myself without branching off from your project? (I like what you've done and don't want to reinvent anything).

**Comment by claar** [comment]
For anything non-standard, I recommend using `Former::checkbox('foo')->raw()->inline()` to output just the bare `<input>`, and outputting any other HTML desired by hand.
