### ISSUE TITLE
[L5] Problem rendering a file input that selects a single file

### ISSUE THREAD

**Issue by londoh** [formers/former#501]
At least I cant seem to find a way to do it. and it seems maybe its not catered for...

in the constructor for File theres this:
```php
    // Multiple files field
    if ($type == 'files') {
        $attributes['multiple'] = 'true';
        $type                   = 'file';
        $name                   = $name.'[]';
    }
```
but if I do this it doesnt work:
```php
    Former::files('image')->accept('png')->multiple('false')
```
because "multiple" can be set to anything or nothing and still work:

or maybe I missed some way of doing it

regards

l.

**Comment by claar** [comment]
Try Former::file('image')

**Comment by londoh** [comment]
perfect!, thanks

just out of curiosity how could I have known that without disturbing you?

**Comment by claar** [comment]
Well, this particular thing is actually in our terrible documentation at https://anahkiasen.github.io/former/#files-handling if you read extra-carefully. If you're so inclined, we'd love for it to be improved. :)

**Comment by londoh** [comment]
doh... yep I found it. 

Point taken, I'll see what I can do

thanks again
