### ISSUE TITLE
Cannot set label on checkboxes

### ISSUE THREAD

**Issue by aleemb** [formers/former#502]
The code for rendering checkboxes doesn't let me set labels, if I have an array:

```
['foo' => ['id' => 'alpha', 'value' => 'beta', 'label' => 'gamma']
```

The label should be `gamma` not `foo`. This behaviour appears to be different from how a single checkbox is rendered which appears to allow setting text separately from the name inside `Checkable.php`.

```

        // Single item
        return $this->createCheckable(array(
            'name'  => $this->name,
            'label' => $this->text,
            'value' => $this->value,
            'attributes' => $this->attributes,
        ));
```

Hope that makes sense.

**Comment by claar** [comment]
Yes, checkables are inconsistent currently, but cannot be easily fixed due to backwards compatibility issues.

You can, however, set the `name` attribute, so you can set labels on checkboxes using syntax like:

```
['My Label' => ['id' => 'alpha', 'name' => 'my_name', 'value' => 'beta', 'label' => 'gamma']
```
