### ISSUE TITLE
Install problem on Laravel 4.2

### ISSUE THREAD

**Issue by birdiebel** [formers/former#503]
Hello,

Here error message when I try to install 

Problem 1
    - Conclusion: remove laravel/framework v4.2.17
    - Conclusion: don't install laravel/framework v4.2.17
    - anahkiasen/former 4.0.0 requires illuminate/translation ~5.0 -> satisfiable by illuminate/translation[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.1
3, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.6, v5.1.8].
    - anahkiasen/former 4.0.1 requires illuminate/translation ~5.0 -> satisfiable by illuminate/translation[v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.1
3, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.6, v5.1.8].
    - don't install illuminate/translation v5.0.0|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.0.22|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.0.25|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.0.26|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.0.28|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.0.33|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.0.4|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.1.1|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.1.13|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.1.16|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.1.2|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.1.20|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.1.22|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.1.25|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.1.6|don't install laravel/framework v4.2.17
    - don't install illuminate/translation v5.1.8|don't install laravel/framework v4.2.17
    - Installation request for laravel/framework == 4.2.17.0 -> satisfiable by laravel/framework[v4.2.17].
    - Installation request for anahkiasen/former ^4.0 -> satisfiable by anahkiasen/former[4.0.0, 4.0.1].

Installation failed, reverting ./composer.json to its original content.

Can you help me ? Thanks

**Comment by claar** [comment]
Use the latest 3.x branch for Laravel 4 -- `composer require anahkiasen/former:~3`
