### ISSUE TITLE
[Laravel 5.2]Session store not set on request

### ISSUE THREAD

**Issue by nandanvrs** [formers/former#504]
ErrorException thrown with message "Session store not set on request. (View: \resources\views\welcome.blade.php)"

Stacktrace:
#50 ErrorException in 
\vendor\laravel\framework\src\Illuminate\Http\Request.php:775
#49 Illuminate\View\Engines\CompilerEngine:handleViewException in \vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php:44
#48 Illuminate\Routing\Router:Illuminate\Routing\{closure} in <#unknown>:0
#47 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in <#unknown>:0
#46 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in <#unknown>:0
#45 Barryvdh\Debugbar\Middleware\Debugbar:handle in <#unknown>:0
#44 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in <#unknown>:0
#43 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in <#unknown>:0
#42 RuntimeException in 
\vendor\laravel\framework\src\Illuminate\Http\Request.php:775
#41 Illuminate\Http\Request:session in \vendor\laravel\framework\src\Illuminate\Http\Request.php:446
#40 Illuminate\Http\Request:old in 
\vendor\anahkiasen\former\src\Former\Former.php:257
#39 Former\Former:getPost in 
\vendor\anahkiasen\former\src\Former\Traits\Field.php:362
#38 Former\Traits\Field:repopulate in 
\vendor\anahkiasen\former\src\Former\Traits\Field.php:105
#37 Former\Traits\Field:__construct in \vendor\anahkiasen\former\src\Former\Traits\Checkable.php:92
#36 Former\Traits\Checkable:__construct in \vendor\anahkiasen\former\src\Former\MethodDispatcher.php:199
#35 Former\MethodDispatcher:toFields in 
\vendor\anahkiasen\former\src\Former\Former.php:154
#34 Former\Former:__call in \vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:216
#33 Former\Former:checkbox in \vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:216
#32 Illuminate\Support\Facades\Facade:__callStatic in \storage\framework\views\0dea5c973b45f3569a9018d437f39bb6453a9c96.php:42

etc ....

**Comment by nandanvrs** [comment]
solved. https://github.com/laravel/framework/issues/11524

**Comment by coolsnow77** [comment]
![image](https://cloud.githubusercontent.com/assets/8206517/14631549/8568de4a-0646-11e6-9652-6c6798ae2c5e.png)

**Comment by coolsnow77** [comment]
please  add  routes.php the up，  web middleware
