### ISSUE TITLE
Erros don't work if Fields are not rendered

### ISSUE THREAD

**Issue by biwerr** [formers/former#506]
If you store the Form fields in an Array the validation errors dont work. 
[
            Former::text('name')->required(),
            Former::textarea('description')->required(),
            Former::text('start')->required()->dataProvide("datepicker"),
            Former::text('end')->required()->dataProvide("datepicker"),
            Former::text('start_registration')->required()->dataProvide("datepicker"),
            Former::text('end_registration')->required()->dataProvide("datepicker"),
            Former::text('last_deregister')->required()->dataProvide("datepicker"),
            Former::text('max_registrations')->required(),
            Former::text('price')->required(),
 ];

The Field->getName() Method call in the Former->getErrors() Method only returns the last created field (in this case 'price').

**Comment by claar** [comment]
Former doesn't know or care that you store its objects in an array, so
something else is going on here. Your example doesn't show a
'Former::open()' call, which is required -- perhaps that's the problem?

**Comment by biwerr** [comment]
open() is called before storing fields in the array, close() is called on the end

**Comment by claar** [comment]
Try adding `->render()` to all calls.

**Comment by biwerr** [comment]
I thought former would call a render method String conversion

**Comment by claar** [comment]
You're right, it does. But the way you're doing it, you're calling `Former::text()` before `Former::open()` has rendered, which doesn't work if I recall.

**Comment by biwerr** [comment]
here is my example code. The open() method is called before form fields, so the form opener should be rendered. 


```
            $form_open = Former::horizontal_open()
                ->id('campaignCreateForm')
                ->secure()
                ->action(route('admin.campaign.update',["id"=>$id]))
                ->method('POST')->__toString();
            Former::populate($c);
            $fields = [
                Former::text('name')->required(),
                Former::textarea('description')->required(),
                Former::text('start')->required()->dataProvide("datepicker"),
                Former::text('end')->required()->dataProvide("datepicker"),
                Former::text('start_registration')->required()->dataProvide("datepicker"),
                Former::text('end_registration')->required()->dataProvide("datepicker"),
                Former::text('last_deregister')->required()->dataProvide("datepicker"),
                Former::text('max_registrations')->required(),
                Former::text('price')->required(),
                Former::button(trans('global.save'))->type('submit')->class('btn btn-success'),
            ];
            $form = implode("",$fields);

            $output = $form_open.$form.Former::close();
```

**Comment by jp7carlos** [comment]
I had the same problem when using live validation (HTML5) with implode().
I has to explicit cas-t (string) on all the fields before imploding. Didn't have time to take a look at the code but it must be something like: 
* new(), render(), new(), render() -> works
* new(), new(), render(), render() -> Doesn't work
