### ISSUE TITLE
Elements doesn't render in L5.2

### ISSUE THREAD

**Issue by igoralbu** [formers/former#507]
I can open() and close() Former, but can't display any other elements. The page keep loading for minutes and shows incomplete HTML.

It works only if I remove VerifyCsrfToken middleware from $middlewareGroups => 'web' in App\Http\Kernel.php.

```
protected $middlewareGroups = [
    'web' => [
        \App\Http\Middleware\EncryptCookies::class,
        \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
        \Illuminate\Session\Middleware\StartSession::class,
        \Illuminate\View\Middleware\ShareErrorsFromSession::class,
     // \App\Http\Middleware\VerifyCsrfToken::class,
    ],
```

Can't find a solution.

**Comment by adriandmitroca** [comment]
I face the same issue. Disabling CSRF protection doesn't work, PHP throws an error:
`[21-Mar-2016 11:27:45 Europe/Warsaw] PHP Fatal error:  Method Former\Form\Fields\Input::__toString() must not throw an exception in /Users/adrian/htdocs/idealny-trawnik/storage/framework/views/fb4d072de190bd90a38a2ea5f48c602263be0008.php on line 0`

**Comment by claar** [comment]
I'm afraid I can't reproduce this -- please post further debugging information if this persists.
