### ISSUE TITLE
Using Vue.js attributes?

### ISSUE THREAD

**Issue by CedNet** [formers/former#508]
Hi! Is it possible to add attributes named "v-if" and "v-on" and so on? I tried with different versions of ->von() but couldn't get it to work.

**Comment by claar** [comment]
You can use `->setAttribute('v-if', 'foo')` for that -- just tested and seems to work.

**Comment by benkelukas** [comment]
Hi, I'm having similiar problem, 
simple `->setAttribute('v-if', 'foo')` works but things like
`->setAttribute('v-on:keyup.enter', 'someMethod')` doesnt. It gets striped out of the field.
Is there some kind of escaping going on? How can I achieve this?

Thanks.
