### ISSUE TITLE
How do I specify the correct config to use when implementing a custom framework?

### ISSUE THREAD

**Issue by SiCoUK** [formers/former#510]
I can't see where I specify the path for the config file for my custom framework. I have published the former config to my Laravel app and I can alter the default config without issue.

However if I use a custom framework (in this instance a small update to Foundation 6) former still looks in the vendor /src/config directory.

If I create a ZurbFoundation6.php file there it works fine, obviously this is wrong! How do I get former to look in app/config/ or my own directory?

Thanks

**Comment by claar** [comment]
Great question.. probably a bug but I'm not sure. I assume this 1.5yr old ticket isn't still a problem, but if someone else has this problem please step through `FormerServiceProvider::getConfigurationFiles` and see if Former handles this correctly.. if not, please reopen this or file a new issue/PR.
