### ISSUE TITLE
Stop validation messages over writting help text

### ISSUE THREAD

**Issue by SiCoUK** [formers/former#511]
Is there anyway to stop the validation error messages (from laravel) over writting the help text for the field. I believe from a usability point of view the help text should still be present.

Can we not have an additional getError() method as well as the getHelp() method.

Or is there a way to overwrite the getHelp() method and spit out two sets of messages?

Thanks

**Comment by claar** [comment]
The way I handle this personally is to add the help text to the error message, like so:

```
Former::text('budget')->help('Please estimate your budget');
$rules = ['budget' => 'min'];
$messages [
            'budget.min' => 'Please estimate your budget. Your budget must be at least :min dollars',
];
```

I agree that it'd be nice to have something more sophisticated, but I'm not sure it's within the scope of Former. I'd welcome a PR attempt though.
