### ISSUE TITLE
Class 'Former' not found (Laravel 5.2.22)

### ISSUE THREAD

**Issue by kristianharmer** [formers/former#512]
Hey,

I'm having issues implementing Former on a new project. Have used it before and never had any issues!

The only difference is this is a newer version if Laravel (5.2.22) which is using the 'Collective\Html\HtmlServiceProvider' instead of 'Illuminate\Html\HtmlServiceProvider'!

I followed the instructions under Laravel 5 but upon using {!! Former::xxx !!} I get:

Class 'Former' not found

... this is coming from my blade file!

Any ideas what I am doing wrong?

Best regards,
Kris...

**Comment by claar** [comment]
Hi Kris,

Sorry you had problems! I just now created a brand new Laravel 5.2.22 site and added Former without issues. Be sure to update app.php as described in the docs at https://github.com/formers/former/wiki/Getting-started

The `class 'Former' not found` normally indicates that the Former facade wasn't added to `config/app.php` properly.

**Comment by kristianharmer** [comment]
Hi, thanks for taking the time to respond.

I've attempted another install and implementation but with the same result.

Here's the contents of my config/apps.php file:

`    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        Illuminate\Auth\AuthServiceProvider::class,
        Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        Illuminate\Cookie\CookieServiceProvider::class,
        Illuminate\Database\DatabaseServiceProvider::class,
        Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        Illuminate\Hashing\HashServiceProvider::class,
        Illuminate\Mail\MailServiceProvider::class,
        Illuminate\Pagination\PaginationServiceProvider::class,
        Illuminate\Pipeline\PipelineServiceProvider::class,
        Illuminate\Queue\QueueServiceProvider::class,
        Illuminate\Redis\RedisServiceProvider::class,
        Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        Illuminate\Session\SessionServiceProvider::class,
        Illuminate\Translation\TranslationServiceProvider::class,
        Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        'Cviebrock\EloquentSluggable\SluggableServiceProvider',
        'Collective\Html\HtmlServiceProvider',

        /*
         * Application Service Providers...
         */
        App\Providers\AppServiceProvider::class,
        App\Providers\AuthServiceProvider::class,
        App\Providers\EventServiceProvider::class,
        App\Providers\RouteServiceProvider::class,
        Former\FormerServiceProvider::class,

    ],

    /*
    |--------------------------------------------------------------------------
    | Class Aliases
    |--------------------------------------------------------------------------
    |
    | This array of class aliases will be registered when this application
    | is started. However, feel free to register as many as you wish as
    | the aliases are "lazy" loaded so they don't hinder performance.
    |
    */

    'aliases' => [

        'App'       => Illuminate\Support\Facades\App::class,
        'Artisan'   => Illuminate\Support\Facades\Artisan::class,
        'Auth'      => Illuminate\Support\Facades\Auth::class,
        'Blade'     => Illuminate\Support\Facades\Blade::class,
        'Cache'     => Illuminate\Support\Facades\Cache::class,
        'Config'    => Illuminate\Support\Facades\Config::class,
        'Cookie'    => Illuminate\Support\Facades\Cookie::class,
        'Crypt'     => Illuminate\Support\Facades\Crypt::class,
        'DB'        => Illuminate\Support\Facades\DB::class,
        'Eloquent'  => Illuminate\Database\Eloquent\Model::class,
        'Event'     => Illuminate\Support\Facades\Event::class,
        'File'      => Illuminate\Support\Facades\File::class,
        'Gate'      => Illuminate\Support\Facades\Gate::class,
        'Hash'      => Illuminate\Support\Facades\Hash::class,
        'Lang'      => Illuminate\Support\Facades\Lang::class,
        'Log'       => Illuminate\Support\Facades\Log::class,
        'Mail'      => Illuminate\Support\Facades\Mail::class,
        'Password'  => Illuminate\Support\Facades\Password::class,
        'Queue'     => Illuminate\Support\Facades\Queue::class,
        'Redirect'  => Illuminate\Support\Facades\Redirect::class,
        'Redis'     => Illuminate\Support\Facades\Redis::class,
        'Request'   => Illuminate\Support\Facades\Request::class,
        'Response'  => Illuminate\Support\Facades\Response::class,
        'Route'     => Illuminate\Support\Facades\Route::class,
        'Schema'    => Illuminate\Support\Facades\Schema::class,
        'Session'   => Illuminate\Support\Facades\Session::class,
        'Storage'   => Illuminate\Support\Facades\Storage::class,
        'URL'       => Illuminate\Support\Facades\URL::class,
        'Validator' => Illuminate\Support\Facades\Validator::class,
        'View'      => Illuminate\Support\Facades\View::class,
        'Form'      => 'Collective\Html\FormFacade',
        'Html'      => 'Collective\Html\HtmlFacade',
        'Former'    => 'Former\Facades\Former',

    ],`

And this is my usage in my blade file:

`
{!! Former::populate( $region ) !!}
				{!!  Former::horizontal_open_for_files()->method('put')->route('manager.regions.update', $region->id) !!}

				{!! Former::close() !!}
`
I ran through the installation, now oin the readme file, and seem to always get:

> FatalErrorException in 99d7f220db2a716556b49deef8d9aae436f7be02.php line 15: Class 'Former' not found

Is there anything else I can try?

Best regards,
Kris...

**Comment by claar** [comment]
Hmm... what's in your `composer.json` for Former? Did you run `composer install` afterwards (unless you used `composer require`, which runs install automatically)?

Here's the process I did to verify things work:

```bash
    laravel new my_project; cd my_project
    composer require anahkiasen/former
    # Modify config/app.php the same as yours above
    # Modify app/Http/routes.php to add the "web" middleware to the welcome route (for session support)
    # Edit resources/views/welcome.blade.php, add:
         {!! Former::open(); !!}
         {!! Former::text('foo'); !!}
         {!! Former::close(); !!}
```

Works just fine for me :/
