### ISSUE TITLE
<checkbox value="false"> prevents true boolean to ever be sent.

### ISSUE THREAD

**Issue by arakash92** [formers/former#520]
I have played with the configuration, but it seems that the value of checkboxes are always "false" for some reason.

This prevents booleans from being sent correctly with regard to Laravel's validation behavior.

Running Laravel 5.2.

**Comment by jp7carlos** [comment]
Hi @afflicto, 
Can you provide some code to reproduce the error, please?

I tested this and it seems to work:
```php
<?= Former::checkbox('foo')->check() ?>
```
```html
<input id="foo" type="checkbox" name="foo" checked="checked" value="1">
```

You might need to take a look at "push_checkboxes" and "unchecked_value" settings.

```php
Former::setOption('push_checkboxes', true);
Former::setOption('unchecked_value', 0);
```

**Comment by younes0** [comment]
It doesn't work and it's depressing @jp7carlos

**Comment by younes0** [comment]
```php
{!! Former::checkbox('is_admin')->check($user->is_admin)->value(1) !!}
```

When you leave the is_admin untouched but checked, $request->get('is_admin') is set to null...

**Comment by claar** [comment]
@younes0 Can you provide some code to reproduce the error? It's working for the rest of us, so it'd be helpful to know what's going on.

**Comment by claar** [comment]
Hey @younes0, thanks for the code example, that helps tremendously.

I just tried `{!! Former::checkbox('is_admin')->check(true)->value(1) !!}`. In my controller method, both `Input::get('is_admin')` and `app('request')->get('is_admin')` return `1`.

Can you post your entire form? Are you outputting (not just calling) `{{ Former::open() }}` before calling `Former::checkbox`?

**Comment by claar** [comment]
Hmm, I just dove into the `check` function:

```
public function check($checked = true)
	{
		// If we're setting all the checked items at once
		if (is_array($checked)) {
			$this->checked = $checked;
			// Checking an item in particular
		} elseif (is_string($checked) or is_int($checked)) {
			$this->checked[$checked] = true;
			// Only setting a single item
		} else {
			$this->checked[$this->name] = (bool) $checked;
		}

		return $this;
	}
```

Is it possible `$user->is_admin` is actually a string or int? That would explain the behavior if so.

**Comment by younes0** [comment]
Thanks for your help @class

This is the blade file
```php
{!! Former::open()->method('PUT')->action('/admin/user/'.$user->id) !!}
{!! Former::populate($user) !!}

@embed('embed._panel')
    @section('title', 'Informations')

    @section('body')
        {!! Former::checkbox('is_enabled')->check($user->is_enabled)->value(1)->text(' ') !!}

        {!! Former::checkbox('is_admin')->check($user->is_admin)->value(1) !!}
    @endsection

    @section('footer')
        {!! Former::actions()->primary_submit('Submit changes') !!}
    @endsection
@endembed

{!! Former::close() !!}
```php

```html
<div class="form-group">
  <div class="col-lg-10 col-sm-8">
    <div class="checkbox">
      <label for="is_enabled" class=""><input id="is_enabled" type="checkbox" name=
      "is_enabled" checked="checked" value="1" /></label>
    </div>
  </div>
</div>

<div class="form-group">
  <div class="col-lg-10 col-sm-8">
    <div class="checkbox">
      <label for="is_admin" class=""><input id="is_admin" type="checkbox" name=
      "is_admin" checked="checked" value="1" /></label>
    </div>
  </div>
</div>
```

With is_admin and is_enabled as boolean (casted as in Model).
Scenario:
1. user->is_admin & user->is_enabled are set to false
2. is_admin & is_enabled are initially not checked, but then human checked 
3. form is submitted: $request->get('is_admin') & $request->get('is_enabled') contain "1" which is the expected behavior ; user->is_admin & user->is_enabled are set to true

4. I get redirected to form, is_admin & is_enabled are initally checked and left untouched
5. form is submitted: $request->get('is_admin') & $request->get('is_enabled') are empty strings ("") which results in an expected behavior

**Comment by younes0** [comment]
`forceValue(1)` solved my issue:
 {!! Former::checkbox('is_enabled')->check($user->is_enabled)->forceValue(1) !!}

**Comment by claar** [comment]
@younes0 Thanks so much for posting that info -- both the reproduction steps and your workaround. If anyone wants to look into this further, we always welcome PRs. Unfortunately the code involved is very brittle -- changing it will likely break other's currently working code. :/

**Comment by younes0** [comment]
Should we specify this workaround in the docs ?

**Comment by claar** [comment]
Not until the problem that causes it is better understood -- this appears to be a repopulation bug of some kind.
