### ISSUE TITLE
Since last update Checkbox is always checked.

### ISSUE THREAD

**Issue by d-lamers** [formers/former#522]
When using populate the checkbox is being checked, even if the value is 0. This used to work and the problem started after the update.

    \Former::populate($shop);

    {{ Former::checkbox('hidden')->value(1) }}

Where $shop->hidden = 0

(Laravel 4)

**UPDATE:** I went back to commit '5a21d2b' and it resolved the issue. So it is definitely in the new version.

**Comment by GC-Max** [comment]
I've noticed this issue too. Reverting to v3.5.9 fixed it for now

**Comment by GC-Max** [comment]
I found using `->forceValue(1)` worked, but it doesn't feel like a good fix. I've reverted for now.

**Comment by claar** [comment]
I can reproduce this, sorry for the trouble. I've reverted #521 for now.

**Comment by GC-Max** [comment]
Thanks. Could you please do a release on the v3 branch as well.

**Comment by claar** [comment]
@GC-Max Unless I'm mistaken, the current v3 releases are fine. v3.5.10 doesn't have issue 521 merged into it.

**Comment by claar** [comment]
Annd I'm mistaken. Sorry, will release 3.5.11.

**Comment by zmonteca** [comment]
I simply turned the config into a string instead of an int.

Laravel Framework version 5.3.30
PHP 7.1.1

config/former.php

`
	// The value a checkbox will have in the POST array if unchecked
	'unchecked_value'         => '0',
`
