### ISSUE TITLE
Add setRaw() 

### ISSUE THREAD

**Issue by CedNet** [formers/former#524]
Hi, could you please allow something like "setRaw()" in order to do some more advanced bindings to the elements? I'm having trouble with the more advanced bindings from Vue JS such as: setAttribute("v-bind:style", "{'disabled': !submitted}") won't render correctly. 

With a setRaw("v-bind:style=\"{'disabled': !submitted}\"") it would be up to me to decide exactly what's rendered.

**Comment by claar** [comment]
Hey @CedNet PRs are always very welcome!
