### ISSUE TITLE
Translate select field name value

### ISSUE THREAD

**Issue by codedge** [formers/former#530]
When using the `select` field from Former like this

```
 {!! Former::select('industry_id')
            ->addOption('','')
            ->fromQuery($industries, 'name', 'id')
            ->help('texts.industry_help') !!}
```

is there a way to tell Former to translate the `name` field in the `fromQuery` method?

**Comment by KuenzelIT** [comment]
As far as I know fromQuery just takes the name and id attributes from the `$industries` objects. If `$industries` is a collection, you could use 
```php
$industries->map(function($item){
    $item->name = trans($item->name);
    return $item;
}) 
```

to translate the name.
