### ISSUE TITLE
IDE auto completion problem

### ISSUE THREAD

**Issue by xfactor5** [formers/former#531]
Hi,
It appears that former is heavily using dynamic methods which prevents IDE auto completion which really degrades the writability of code, while using dynamic methods IDE helper files or method stubs or some inherit doc should be used.
It appears that former is properly documented so I think a few inheritdoc statements and method stubs will do the trick.
Thanks

**Comment by claar** [comment]
Yep, I agree -- I would happily merge any PRs to improve Former's IDE compatibility.
