### ISSUE TITLE
[L5] Checkboxes removed on validation redirect withInput

### ISSUE THREAD

**Issue by biwerr** [formers/former#534]
I have some Problems with generating Checkboxes to attach Roles to a specific User. If the validation fails laravel redirects the request to the edit form withInput(), but Former ignores the available roles and displays only the selected roles.
## Method 1

```
$groups = [];
        foreach(Role::all() as $role)
        {
            $groups[$role->name]=[
                'value' => $role->id,
                'checked' => $model->hasRole($role->name),
                'name' => 'roles_selection['.$role->name.']',
            ];
        }
$form.= Former::checkboxes('roles_selection[]',"Roles",$groups);
```

**On Edit**
![image](https://cloud.githubusercontent.com/assets/6122710/18204995/fb328268-711f-11e6-810d-2f8f4905b8e8.png)

**After Redirect withInput()**
![image](https://cloud.githubusercontent.com/assets/6122710/18205055/4d562c16-7120-11e6-8e88-67b67bdc3af6.png)
## Method 2

`$form.= Former::checkboxes('roles[]',"label",Role::all()->lists('name','id')->toArray());`
I have tried to use the relation ($user->roles), but on i got a rendering error if i try this
`Method Former\Form\Fields\Checkbox::__toString() must not throw an exception`

Error is thrown at: getGroupIndexFromItem() because there is no count index in array $item. Count Index is only set if $item->values is type of array (see [Checkable.php#L94](https://github.com/formers/former/blob/d97f907741323b390f43954a90a227921ecc6b96/src/Former/Traits/Checkable.php#L94))

![image](https://cloud.githubusercontent.com/assets/6122710/18205564/ef61b92e-7122-11e6-9675-eb1c5fc18180.png)

```
public static function getGroupIndexFromItem($item)
    {
        $groupIndex = preg_replace('/^.*?\[(.*)\]$/', '$1', $item['name']);
        if (empty($groupIndex) or $groupIndex == $item['name']) {
            return $item['count'];
        }

        return $groupIndex;
    }
```

**Comment by claar** [comment]
Try something like this?

```
$groups = [];
$checked = [];

foreach(Role::all() as $role) {
    $groups[$role->name]=[
        'value' => $role->id,
        'name' => 'roles_selection['.$role->id.']',
    ];
    $checked[$role->id] = $model->hasRole($role->name),
}
$checkboxes = Former::checkboxes('roles_selection[]', "Roles", $groups);
foreach ($checked as $check) {
    $checkboxes = $checkboxes->check('roles_selection['.$role->id.']');
}
$form.= $checkboxes;
```

**Comment by claar** [comment]
Here's a few working examples I keep around in my example file if it helps:

```
<?= Former::checkboxes('asd[]')->checkboxes([
    'foo' => ['name' => 'asd[0]', 'value' => 'XX'],
    'bar' => ['name' => 'asd[1]', 'value' => 'YY'],
]) ?>

<?= Former::checkbox('invmethod')->text('hi') ?>


<?= Former::checkboxes('hehe')->grouped()->checkboxes(['A' => 'foo[1]', 'B' => 'foo[2]'])->check('foo[2]') ?>
<?= Former::checkboxes('blahblah[]')->checkboxes([
    'A' => 'foo[1]',
    'B' => 'foo[2]',
    'C' => 'foo[3]',
    'D' => 'foo[4]',
])->check('foo[2]')->check('foo[3]') ?>
```

**Comment by claar** [comment]
For method 2, try:

`$form.= Former::checkboxes('roles[]')->checkboxes(Role::lists('name','id')->all());`

**Comment by biwerr** [comment]
Method 1: works for me, but i have one question: In Groups array the role->name is uses as key whereas role->id is used in the checked array. Is that because the Key/Value is flipped in the Checkable Trait?

Method2:
@claar with this, the current user roles are not checked
`$form.= Former::checkboxes('roles[]',"Roles",[])->checkboxes(Role::lists('name','id')->all());`

**Comment by claar** [comment]
Closing old issues. Please reopen if needed.
