### ISSUE TITLE
Remove search field in select

### ISSUE THREAD

**Issue by ddela-cr** [formers/former#535]
Hi,

I was wondering if it is possible to remove the search field in the select element? I couldn't find it in the docs

Thanks

**Comment by claar** [comment]
Hi @ddela-cr -- Sorry for the late response. If I'm understanding your question correctly, Former can't help with this.

Former::select` doesn't render a search field -- it simply outputs a `<select>` element in HTML. You might be seeing a search capability of your browser, or perhaps you're using a javascript plugin like select2 to provide search capabilities.

Consider posting a screenshot and more information here or on stackoverflow.com for assistance.
