### ISSUE TITLE
Laravel 5.4 not working

### ISSUE THREAD

**Issue by JoshZA** [formers/former#539]
Caused by method rename on anahkiasen\former\src\Former\Form\Elements.php:46

`GetToken()` needs to be changed to `token()`

**Comment by claar** [comment]
@JoshZA Could you check if https://github.com/formers/former/pull/537 works for you? I keep meaning to merge but haven't had time to test.

**Comment by JoshZA** [comment]
@claar Works fine :thumbsup:

**Comment by claar** [comment]
Merged, thanks @JoshZA!
