### ISSUE TITLE
How to populate nested arrays?

### ISSUE THREAD

**Issue by elephantux** [formers/former#549]
I have translatable (dimsav/translatable) fields in form but populate don't work on it. Now my code look like that:
```
{!! Former::textarea($locale.'[how]')->label('Кто')->rows(6)->value(isset($quest) && isset($quest->translate($locale)->how)?$quest->translate($locale)->how:'') !!}
{!! Former::textarea($locale.'[who]')->label('Как')->rows(6)->value(isset($quest) && isset($quest->translate($locale)->who)?$quest->translate($locale)->who:'') !!}
{!! Former::textarea($locale.'[when]')->label('Когда')->rows(6)->value(isset($quest) && isset($quest->translate($locale)->when)?$quest->translate($locale)->when:'') !!}
```

Is any solution to do it more pretty?

**Comment by Anahkiasen** [comment]
If I recall `$locale.'.how` (ie. dot notation) should work but not sure

**Comment by elephantux** [comment]
In value? Or what you mean in "recall"?

**Comment by elephantux** [comment]
No it didn't work
```
{!! Former::textarea($locale.'.how')->label('How') !!}
```

**Comment by claar** [comment]
Thanks for the question, @elephantux.

Unfortunately, the translation code hasn't been touched in years, and I've never used it so I'm afraid I'm not much help.

Anyone who wishes to help should contribute documentation at https://github.com/formers/former/wiki/Features#localization-helpers and/or PRs to improve Former's behavior.

If you find behavior that doesn't match the documentation, please file specific issues.
