### ISSUE TITLE
How to achieve Inline Multiple select boxed

### ISSUE THREAD

**Issue by john5db** [formers/former#553]
HI , 

I want to add two select boxes with additional label in  in one line . 
Ex.
``
Price -  From |____|           To  |____|    
``
 Here "Price" is additional label.
"From" + "To" are  select boxes.

How can i achieve this type of structure with former.
I did not found any documentation for this. Please guide me..

Thanks

**Comment by claar** [comment]
For anything non-standard, I recommend using Former::select('foo')->raw()->inline() to output just the bare <input>, and outputting any other HTML desired by hand.
