### ISSUE TITLE
How can i disable the wrap-method?

### ISSUE THREAD

**Issue by debrouchee** [formers/former#559]
Hi, i'm using the former-package with a custom framework-class. If i generate an input-element, the package always wraps this elements with a div-container:

`<div><input type="text" name="email"></div>`

Is it possible do deactivate this wrapping-feature? I can prevent this by using the "nude"-Framework, but i want preserve the main functionality. Maybe it's possible to extend the isUnwrappable()-method in the Field-Class ...

**Comment by claar** [comment]
Is `Former::input('foo')->raw()` what you're looking for?

**Comment by debrouchee** [comment]
Okay, that works! Thanks! A great package!

It would be nice to make the wrapping-feature configurable or to get more control over the html-output. In my custom former-framework i only need to generate raw input-elements with some default features of the package: populate, required, error-handling. For example: i havent's seen a possibility to place the additionally css-classes direct on the input-element:

`<input type="text" name="emai" class="required error">`
