### ISSUE TITLE
Class 'Button' not found

### ISSUE THREAD

**Issue by ajimatahari** [formers/former#560]
an Error comes when i try to used :  

`<?= Former::actions( Button::submit('Submit'), Button::reset('Reset') ) ?>`

but everything other than button is working

error Message : Class 'Button' not found

**Comment by claar** [comment]
Hi @ajimatahari,

Good catch -- our documentation appears to be out of date on this.

Until it's updated, please try the following syntax instead:

```
<?= Former::actions(Former::primary_submit('Submit'), Former::default_reset('Reset')) ?>
```

**Comment by ajimatahari** [comment]
done, thanks a lot
