### ISSUE TITLE
Form with multiples and errors not marked

### ISSUE THREAD

**Issue by syphernl** [formers/former#561]
I have a form element:
```
{!! Former::files('attachments')->max(5, 'MB')->accept('application/pdf', 'images')
```

And a validator:
```
'attachments.*' => ['sometimes','mimes:pdf,png', 'max:5242880']
```

When I upload a different filetype (e.g. a mp4 file), the form validation fails but never marks the `attachments` field as failed.

**Comment by claar** [comment]
Hi @syphernl,

What version of Laravel are you using? Can you post a dump of `$validator->errors()` from your controller? As you may know, Laravel handles the validation rules while Former simply tries to match errors to the correct field.

**Comment by syphernl** [comment]
I'm using the latest stable of v5.5.28. The errors include messages like (from the top of my head):
```
attachments.0 => 'Error here',
attachments.1 => 'Error here',
```
I am aware that the `->accept(..)` thing has nothing to do with the backend validation.

**Comment by syphernl** [comment]
@claar Not sure if it matters but we use `$this->validate($rules, $messages)` in our controller. 

The `$requests` variable passed on to the view contains the following:
```
 Illuminate\Support\ViewErrorBag Object
(
    [bags:protected] => Array
        (
            [default] => Illuminate\Support\MessageBag Object
                (
                    [messages:protected] => Array
                        (
                            [attachments.0] => Array
                                (
                                    [0] => The attachments.0 must be a file of type: pdf, xls, doc, docx, xlsx, jpeg, jpg, png, eml.
                                )

                        )

                    [format:protected] => :message
                )

        )

)
```

**Comment by claar** [comment]
Sorry for the delay.

From my testing, the solution appears to be changing your validation rule to:

```'attachments' => ['sometimes','mimes:pdf,png', 'max:5242880']```

If you debug `Illuminate\Validation\Validator::validate()`, you'll see that the `.*` notation messes up the `Illuminate\Validation\Validator::isValidatable()` call's ability to find the right value for the field for validation.

Either way, this doesn't appear to be a Former problem from what I can tell -- please post more if you determine otherwise.

**Comment by syphernl** [comment]
Hi @claar. For some reason the validation never passes if I do it like this. 

The form is only passing validation if I use `attachments.*`. The form fields are however never marked as being incorrect in case an incorrect file (e.g. mp4) is uploaded.
