### ISSUE TITLE
PhpStorm Autocomplete issue

### ISSUE THREAD

**Issue by ztdan4ik** [formers/former#563]
Hi all!
A have install your extension and using it us stand alone application.
Is impossible to setup phpstorm for showing an autocompletion? 

It will be very helpfull, coz I didn't find documentation about full functionality, only examples in wiki and readme. 

Many tkanks!

![1516984555](https://user-images.githubusercontent.com/14123515/35450155-dbac420e-02c7-11e8-882f-19b4e2f66dcf.png)

**Comment by claar** [comment]
Saving this file at the root of your project will help a little bit; still not perfect though: https://gist.github.com/claar/6bb960fe367bfa0308692f506dec8d23
