### ISSUE TITLE
Bootstrap 4 Support

### ISSUE THREAD

**Issue by sarfraznawaz2005** [formers/former#564]
Thanks for the great package !

Any chance of implementing BS4 support soon now that stable version of it is out ?

Thanks

**Comment by claar** [comment]
This is on my mind as well, but I haven't heard of anyone wanting to take a
stab at bootstrap 4 support.

**Comment by sarfraznawaz2005** [comment]
Thanks, I think it would be useful as BS4 will be there for quite few years now :) and soon people would be asking for its support naturally. Thanks

**Comment by kikoseijo** [comment]
Anyone done any work on this thats so kind to share? 👯

**Comment by kikoseijo** [comment]
If anybody interested,

as a contribution, I have here [Bulma.io](http://bulma.io), was done few months ago before bootstrap flex version was released.

[Bulma.io Framework](https://gist.github.com/kikoseijo/adbd0527fffcdc59348ec4d562717cf0)

**Comment by dhsont** [comment]
I am also waiting BS4 Support

**Comment by kikoseijo** [comment]
This is what im using, checkboxes not aligning properly, but it does the job,

https://github.com/kikoseijo/klaravel/blob/master/src/Utils/FormerBootstrap4.php

**Comment by claar** [comment]
@kikoseijo Thanks for pointing that out! Does anyone feel up to turning that code into a PR for this project? Even with bad checkbox alignment it's better than nothing! Appears to be MIT licensed.

**Comment by kikoseijo** [comment]
Hummmm, I don't mind, but not good at tests, and think you have it all with tests-

I mean, I can put that as a feature branch, and maybe someone with a more knowledge of how this framework works can help us out-.-

**Comment by kikoseijo** [comment]
You see, im not experienced, 
can't even run the test by doing the typical `phpunit`

Cloned the repo here:
https://github.com/kikoseijo/former

**Comment by bdewong** [comment]
I know this is a little old but I just added a pull request #577. No tests but it fixed the alignment in the checkboxes.

**Comment by claar** [comment]
Bootstrap 4 support is now released in [4.1.8](https://github.com/formers/former/releases/tag/4.1.8) thanks to @bdewong. Please give it a try!
