### ISSUE TITLE
Add method to create new field from string

### ISSUE THREAD

**Issue by dariusj18** [formers/former#570]
Give the ability to create a new element.

ex. `Former::field($fieldType)`

The reason to do it this way instead of `Former::$fieldType` is because you can't do this `Former::$obj->getFieldType()`. Also it makes it so if some sort of sanitation is require it can be handled behind the scenes.

**Comment by claar** [comment]
To get the type and class of a created element, you can currently use:

```
1. Type of text is {{ Former::text('test')->getType() }}<br>
2. Class of text is {{ get_class(Former::text('test')) }}

// Output:
1. Type of text is text
2. Class of text is Former\Form\Fields\Input
```

Does that help?

**Comment by dariusj18** [comment]
I think you misunderstood my intent.

The idea is to allow creation  of an element with `Former::field('text', 'fieldname')` in addition to `Former::text('fieldname')`

**Comment by claar** [comment]
Hi @dariusj18 -- sorry about that. I did understand your request, but I'm trying to understand your reasoning for the request.

You said that the reason to add this new syntax was to be able to run `Former::$obj->getFieldType()` and for "some sort of sanitation" to be handled behind the service. I'm not understanding what you mean by these benefits -- can you expand on your thoughts?

**Comment by dariusj18** [comment]
`Former::$obj->getFieldType()` throws an error in PHP.

The sanitization was just an extra reason it _might_ be useful.

**Comment by claar** [comment]
What is `Former::$obj`? I'm not following you I'm afraid.

**Comment by dariusj18** [comment]
If I have object `$obj` with method `getFieldType`.  (In this case `$obj` is an object I have to assemble the form from database fields.)

Currently I can run

```
$fieldType = $obj->getFieldType()
Former::$fieldtype($obj->getFieldName)
```

however I would like to accomplish this in one line.  I propose a new method signature on the \Former\Former class.  My name might not be ideal, but as an example `createFieldByType`

you could add it to the __call, 

```
if($method == 'createFieldByType') {
  $fieldType = array_shift($parameters);
  $field = $this->dispatch->toFields($fieldType, $parameters)
} else {
  $field = $this->dispatch->toFields($method, $parameters);
}
```

then my code would look like this

```
Former::createFieldByType($obj->getFieldType(), $obj->getFieldName)
```

**Comment by claar** [comment]
Gotcha.. that makes way more sense.

I agree that such a feature could be useful, but I don't see a trivial way to add it at the moment and I don't have a ton of time to devote to this project.

A PR would be welcome and should include 100% test coverage.
