### ISSUE TITLE
Former Twitter Bootstrap 4 Not working 

### ISSUE THREAD

**Issue by JohnPrakashLobo** [formers/former#578]
Thanks for the nice library for laravel form builder.I have installed latest version of former But i dont see any  bootstrap 4 configuration in former.php .It contain only bootstrap 3 and other framework configuration 

I have also added TwitterBootstrap4 in config but its throwing error but Former\Framework contain TwitterBootstrap4 class in my vendor folder

`	'framework'               => 'TwitterBootstrap4',`

Is there any way to configure bootstrap 4.I am using laravel 5.7

Thanks

**Comment by claar** [comment]
Hi @JohnPrakashLobo,

Sorry about that. I have just now released a new version of Former that contains a default configuration for TwitterBootstrap4. Please update to Former version 4.1.9 and see the changes in `former.php` to see what you need to add to your `former.php` config file.

**Comment by JohnPrakashLobo** [comment]
@claar Thanks for quick fix
