### ISSUE TITLE
Can Former be used outside/without Laravel?

### ISSUE THREAD

**Issue by benrogmans** [formers/former#582]
How can Former be used stand alone? Which class to instantiate/call?

**Comment by Anahkiasen** [comment]
You can use the Facade outside of Laravel and it'll bootstrap its own container if need be IIRC

**Comment by benrogmans** [comment]
Hmm sorry I can't get it to work. Could you provide an example please? 

I've tried many things, like:
`\Former\Facades\Former::framework('TwitterBootstrap3');`
And:
`\Former\Former::framework('TwitterBootstrap3');`

But an error is thrown: class not found

**Comment by benrogmans** [comment]
I'm sorry, my mistake, I didn't update the parent's composer package 🥇  using the Facade works great!
