### ISSUE TITLE
Bootstrap 4 throws error without open and close tag

### ISSUE THREAD

**Issue by CedNet** [formers/former#588]
Wanted to switch over to Bootstrap 4 and when I do that any page that has a use of {!! Former::x() !!} (without an open and close tag) throws an error "Class former.form does not exist" in the file at line 254: 

public function getGroupClasses()
    {
        if ($this->app['former.form']->isOfType('horizontal')) {
            return 'form-group row';
        } else {
            return 'form-group';
        }
    }

I use the Former to generate some random inputs on screen without the need of an actual full form. Can I somehow get around this?

It worked fine in Bootstrap 3. 

I can't myself figure it out or I'd have send a PR.

I'm using the default former.php config file.

**Comment by CedNet** [comment]
I found the issue and sent in a PR for a fix. Tests have passed and the fix is simple enough to just check whether former.form exists before checking type. Hence making it optional to define an opening tag (how it works with Boostrap3)

**Comment by claar** [comment]
Hi @CedNet,

Thanks so much for the issue report and PR. The `Former::open()` call isn't currently optional. There are multiple places in the codebase that depend on `open()` having been called before using other classes such as `Former::checkbox('foo')`.

Changing this assumption would be a welcome PR, but I imagine it would be a large effort. This package is currently only offering maintenance support at the moment, not new development, so such a change would have to come from others.

Thank you!
