### ISSUE TITLE
How to style checkboxes

### ISSUE THREAD

**Issue by bschooly** [formers/former#594]
Specifically how to get a space between checkbox and label?

**Comment by claar** [comment]
Hi @bschooly - I'm sorry the checkbox isn't rendering correctly. Former's job is to output the correct Bootstrap (or other framework) HTML, and it's the framework's job to style the elements.

If your checkbox isn't being styled correctly, please double-check that you have selected your correct framework in Former's `config/former.php` config file. If it's still wrong, please post to this ticket:

1. What version of Former you are using
2. What version of Bootstrap (or another framework) you are using
3. The Former code you are using to generate the checkbox (`Former::checkbox('foo')`, for example)
4. The HTML output is being generated by Former.
5. A screenshot of the checkbox that is not being rendered correctly.

**Comment by bschooly** [comment]
Wow thanks for quick response. 

1. The changelog file newest entry says 4.0.0. Somewhere else to look.
2. Bootstrap 4.5.0
3. {!! Former::checkboxes('Options')->checkboxes($options['items'])->check($options['selected'])!!}
4.  
![Capture](https://user-images.githubusercontent.com/8985668/88303451-ac0ab900-cccc-11ea-9c9f-9e62e655c152.PNG)

**Comment by bschooly** [comment]
Well actually still had framework set to bootstrap3. Changing to 4 results in error. Do I need the latest former?

**Comment by claar** [comment]
Hi @bschooly - what error are you seeing? You can find out what version of Former you are using by looking in your `composer.lock` file -- you should see something like:

```
             "name": "anahkiasen/former",
             "version": "4.4.0",
```

Support for Bootstrap 4 was added in October 2018 in Former version `4.1.8`, so you will have to be on that version or higher.

**Comment by bschooly** [comment]
4.0.5 so I've got upgrade and that in turn will probably mean upgrading laravel as I'm way behind on it for my application.

**Comment by stayallive** [comment]
Closing this issue because it is quite old and it has been a long time since there was any activity, if there is still a problem please open a new issue.
