### ISSUE TITLE
_method

### ISSUE THREAD

**Issue by bschooly** [formers/former#610]
I have a case where no matter what I do former refuses to set _method=PUT, Always sets to POST even though I use -->method('PUT') in the open call.

What circumstances does it honor/not honor the value passed?

**Comment by tortuetorche** [comment]
Hi @bschooly,

Can you send us a full example, please?

Cheers,
Tortue Torche

**Comment by bschooly** [comment]
I don't recall the specifics now, only that I got around them, or perhaps my interpretation of what was happening was incorrect. Closing this ticket. If I can recreate the issue later (later) I'll create a new ticket with more details.
