### ISSUE TITLE
Populate checkboxes from Eloquent relation

### ISSUE THREAD

**Issue by cviebrock** [formers/former#63]
I have a User model with many-to-many relation to Roles.  In my controller:

``` php
$user = User::with('roles')->find($id);

$roles = array();
foreach (Role::all() as $role) {

    $roles[] = array(
        'label' => $role->name,
        'checked' => $user->has_role($role->name)  // boolean if user has the role
    );
}

Former::populate( $user );
Former::populateField( 'roles', $roles  );
```

And in my view:

```
{{ Former::checkboxes('roles') }}
```

It obviously doesn't work, but what I'm hoping to get is a list of checkboxes, one for each of all the Roles (labelled with the `$role->name`, valued with `$role->id`) and those that exist for the current user are checked.

Is there an easy way to do this?

**Comment by biwerr** [comment]
You have to add [] to the fieldname and pass an array with Key,Value to the function

Former::checkboxes('roles[]',"label",Role::all()->lists('name','id')->toArray());
