### ISSUE TITLE
Docs mentions Input::old

### ISSUE THREAD

**Issue by AndreasHeiberg** [formers/former#82]
Hey love the work,

Used to use Former with L3 and fields populated them selves when refreshing with validation errors. However this no longer works. I thought I would simply have to start flashing inputs, but that didn't fix it. The docs didn't really help me, as they suggest Input::old('email') should work, which it doesn't seam to do. 

Sorry for bothering you with something that might not be a problem with Former.

**Comment by claar** [comment]
Closing old inactive issues to make project maintainable.
