### ISSUE TITLE
Add "expanded" option to select

### ISSUE THREAD

**Issue by atrauzzi** [formers/former#98]
This is going to sound crazy, but if you could add an option called 'expanded' to the select which would cause it to render as a series of labelled checkboxes....

This option is popular in a lot of form libraries both client and server side (sfWidgetFormDoctrineChoice in Symfony 1.4, dojox/form/CheckedMultiSelect in Dojo) and is extremely useful for creating nice scrollable interfaces.

**Comment by claar** [comment]
Closing old inactive issues to make project maintainable.
